/*----------------------------------------------------------------------------*/
/**
   @file    spjgui.c
   @author  Y. Jung
   @date    Jan 2003
   @version	$Revision: 1.3 $
   @brief   Graphical user interface for spjitter
*/
/*----------------------------------------------------------------------------*/

/*
	$Id: spjgui.c,v 1.3 2003/01/10 13:15:31 yjung Exp $
	$Author: yjung $
	$Date: 2003/01/10 13:15:31 $
	$Revision: 1.3 $
*/

/*-----------------------------------------------------------------------------
   								Includes
 -----------------------------------------------------------------------------*/

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>

/*-----------------------------------------------------------------------------
                                Static TCL code
 -----------------------------------------------------------------------------*/
static char tcl_code[] =

"proc errorMessage { string_arg } {global var\n"
"global but_font\n"
"set win [toplevel .window]\n"
"wm title .window \"Error message\"\n"
"frame $win.err -background white -borderwidth 10 -cursor pirate -height 100 -width 60\n"
"label $win.err.lab -background black -borderwidth 5 -font $but_font -foreground white -relief sunken -text $string_arg -width 60 -wraplength 500\n"
"button $win.err.but -activebackground red -activeforeground black -background blue -borderwidth 5 -command \"set var 1\" -font $but_font -foreground white -relief groove -text Ok\n"
"pack $win.err -side top\n"
"pack $win.err.lab -side top\n"
"pack $win.err.but\n"
"tkwait variable var\n"
"destroy $win\n"
"return}\n"
"catch {exec rm tclIndex}\n"
"lappend auto_path [exec dirname [exec which $argv0]]\n"
"proc mainProg {} {global but_act_back_col\n"
"global but_back_col\n"
"global but_fore_col\n"
"global lab_back_col\n"
"global but_font\n"
"global argv\n"
"global argc\n"
"global currentfile\n"
"global topc\n"
"set but_act_back_col cyan3\n"
"set but_back_col cyan2\n"
"set but_fore_col blue\n"
"set lab_back_col SkyBlue1\n"
"set but_font 8x13bold\n"
"set currentfile \"No Name\"\n"
"wm title . \"spjitter.ini configuration\"\n"
"frame .mbar -relief raised -background $lab_back_col -borderwidth 2\n"
"menubutton .mbar.file -activebackground $but_act_back_col -activeforeground black -background $but_back_col -font $but_font -foreground $but_fore_col -relief raised -text File -menu .mbar.file.menu\n"
"menu .mbar.file.menu -tearoff 0\n"
".mbar.file.menu add command -label \"Open...\" -command \"openFile\"\n"
".mbar.file.menu add command -label \"New\" -command \"newFile\"\n"
".mbar.file.menu add command -label \"Save\" -command \"saveFile\"\n"
".mbar.file.menu add command -label \"Save as...\" -command \"saveAsFile\"\n"
".mbar.file.menu add separator\n"
".mbar.file.menu add command -label \"Exit\" -command exit\n"
"menubutton .mbar.opti -activebackground $but_act_back_col -activeforeground black -background $but_back_col -font $but_font -foreground $but_fore_col -relief raised -text \"Options\" -menu .mbar.opti.menu\n"
"menu .mbar.opti.menu -tearoff 0\n"
".mbar.opti.menu add cascade -label \"Fonts\" -menu .mbar.opti.menu.fonts\n"
".mbar.opti.menu add cascade -label \"Colors\" -menu .mbar.opti.menu.color\n"
"menu .mbar.opti.menu.fonts -tearoff 0\n"
".mbar.opti.menu.fonts add command -label \"Fixed\" -command \"modFont fixed .\"\n"
".mbar.opti.menu.fonts add command -label \"Helvetica\" -command {\n"
"		if {[catch {modFont -*-helvetica-medium-r-normal-*-14-*-*-*-*-*-iso8859-* .}] == 1 } {\n"
"			modFont fixed .\n"
"		}\n"
"	}\n"
".mbar.opti.menu.fonts add command -label \"HelveticaBold\" -command {\n"
"		if {[catch { modFont -adobe-helvetica-bold-r-normal--14-140-75-75-p-82-iso8859-1 .}] == 1 } {\n"
"			modFont fixed .\n"
"		}\n"
"	}\n"
".mbar.opti.menu.fonts add command -label \"Lucida\" -command {\n"
"		if {[catch { modFont -b&h-lucidatypewriter-bold-r-normal-sans-14-140-75-75-m-90-iso8859-1 .}] == 1 } {\n"
"			modFont fixed .\n"
"		}\n"
"	}\n"
".mbar.opti.menu.fonts add command -label \"Fixed2\" -command {\n"
"		if {[catch { modFont -misc-fixed-medium-r-normal--14-110-100-100-c-70-iso8859-1 .}] == 1 } {\n"
"			modFont fixed .\n"
"		}\n"
"	}\n"
"menu .mbar.opti.menu.color -tearoff 0\n"
".mbar.opti.menu.color add command -label \"Black & White\" -command {modCol b&w}\n"
".mbar.opti.menu.color add command -label \"Color\" -command {modCol col}\n"
"button .mbar.help -activebackground $but_act_back_col -activeforeground black -background $but_back_col -font $but_font -foreground $but_fore_col -relief raised -text Help -command {\n"
"			if { $spjitter_install == 0 } {\n"
"				errorMessage \"Cannot execute spjitter => no help file\"\n"
"				return\n"
"			}\n"
"			catch {exec spjitter -g -f help_gui.ini}\n"
"			ini2Help help_gui.ini help_gui.txt\n"
"			roWin \"Help file\" help_gui.txt \n"
"			exec rm -f help_gui.txt\n"
"			exec rm -f help_gui.ini\n"
"		}\n"
"label .file_selected -background $lab_back_col -borderwidth 2 -font $but_font -foreground black -relief flat -textvariable currentfile\n"
"set topc [canvas .canv -yscrollcommand \".scrolly set\"]\n"
"scrollbar .scrolly -orient vertical -command \"$topc yview\"\n"
"pack .scrolly -fill y -side right\n"
"pack $topc -fill both -expand true -side bottom\n"
"pack .mbar -side top -fill x\n"
"pack .mbar.file -side left\n"
"pack .mbar.opti -side left\n"
"pack .mbar.help -side right\n"
"pack .file_selected -side top -fill x\n"
"if { $argc > 0 } {if { [lindex $argv 0] == \"-\" } {if { $argc > 1 } {set currentfile [lindex $argv 1]\n"
"pack .file_selected\n"
"file2Array\n"
"displayArray}} else {set currentfile [lindex $argv 0]\n"
"pack .file_selected\n"
"file2Array\n"
"displayArray}}}\n"
"proc Start {} {global spjitter_install\n"
"global but_font\n"
"set lit_font 8x13\n"
"set but_font 8x13bold\n"
"set spjitter_install 1\n"
"if [catch {set ecl_version [exec spjitter --version]} resId] {errorMessage \"Cannot execute spjitter --version\"\n"
"set spjitter_install 0\n"
"set ecl_version \"?\"}\n"
"frame .f\n"
"label .f.l -text \"Welcome to GUI for the spjitter\"\n"
"pack .f.l -in .f -side top\n"
"label .f.l2 -text \"This GUI supports eclipse version 4.5.0\" -font $lit_font\n"
"pack .f.l2 -in .f -side top\n"
"label .f.l3 -text \"$ecl_version\" -font $lit_font\n"
"pack .f.l3 -in .f -side top\n"
"button .f.b -text \"Start GUI\" -command {\n"
"		destroy .f\n"
"		mainProg\n"
"    }\n"
"pack .f.b -in .f -side top -expand 1 -fill both\n"
"button .f.b2 -text \"Exit\" -command exit\n"
"pack .f.b2 -in .f -side top\n"
"pack .f}\n"
"Start\n"
"proc roWin {title file} {if { ![file exists $file] } {errorMessage \"Cannot find $file\"\n"
"return}\n"
"if { [winfo exists .rowindow] == 1 } {destroy .rowindow}\n"
"toplevel .rowindow\n"
"wm title .rowindow $title\n"
"frame .rowindow.t\n"
"text .rowindow.t.text -relief sunken -bd 2 -yscrollcommand \".rowindow.t.scr_help set\"\n"
"scrollbar .rowindow.t.scr_help -command \".rowindow.t.text yview\"\n"
"pack .rowindow.t.scr_help -side right -fill y\n"
"pack .rowindow.t.text -fill both -side left -expand true\n"
"pack .rowindow.t -fill both -side top -expand true\n"
"loadFile .rowindow.t.text $file\n"
"button .rowindow.b -text Dismiss -command { destroy .rowindow }\n"
"pack .rowindow.b -side bottom -anchor s}\n"
"proc loadFile {win file} {$win delete 1.0 end\n"
"set f [open $file]\n"
"while {![eof $f]} {$win insert end [read $f 1000]}\n"
"close $f}\n"
"proc modFont {font widget} {set child [winfo children $widget]\n"
"foreach x $child {if { ([winfo class $x] == \"Label\") } {$x config -font $font} elseif {[winfo class $x] == \"Entry\"} {$x config -font $font} elseif {[winfo class $x] == \"Button\"} {$x config -font $font} elseif {[winfo class $x] == \"Checkbutton\"} {$x config -font $font} elseif {[winfo class $x] == \"Radiobutton\"} {$x config -font $font} elseif {[winfo class $x] == \"Frame\"} {modFont $font $x} elseif {[winfo class $x] == \"Canvas\"} {modFont $font $x}}\n"
"return}\n"
"proc modCol { col_type } {global but_act_back_col\n"
"global but_back_col\n"
"global but_fore_col\n"
"global lab_back_col\n"
"if { $col_type == \"col\" } {set but_act_back_col cyan3\n"
"set but_back_col cyan2\n"
"set but_fore_col blue\n"
"set lab_back_col SkyBlue1} elseif {$col_type == \"b&w\"} {set but_act_back_col white\n"
"set but_back_col white\n"
"set but_fore_col black\n"
"set lab_back_col white}\n"
".mbar config -background $lab_back_col\n"
".mbar.file config -activebackground $but_act_back_col -background $but_back_col -foreground $but_fore_col\n"
".mbar.opti config -activebackground $but_act_back_col -background $but_back_col -foreground $but_fore_col\n"
".mbar.help config -activebackground $but_act_back_col -background $but_back_col -foreground $but_fore_col\n"
".file_selected config -background $lab_back_col\n"
"return}\n"
"proc greyOut {widget} {global children\n"
"set children [winfo children $widget]\n"
"foreach x $children {if { ([winfo class $x] == \"Label\") } {$x config -foreground grey50} elseif {[winfo class $x] == \"Entry\"} {$x config -state disabled\n"
"$x config -foreground grey50} elseif {[winfo class $x] == \"Button\"} {$x config -state disabled} elseif {[winfo class $x] == \"Checkbutton\"} {$x config -state disabled} elseif {[winfo class $x] == \"Radiobutton\"} {$x config -state disabled} elseif {[winfo class $x] == \"Frame\"} {greyOut $x} elseif {[winfo class $x] == \"Canvas\"} {} elseif {[winfo class $x] == \"Scrollbar\"} {}}\n"
"return}\n"
"proc greyIn {widget} {global topc\n"
"global children\n"
"global classi_source\n"
"global wavecal_arc\n"
"set children [winfo children $widget]\n"
"foreach x $children {if { ([winfo class $x] == \"Label\") } {$x config -foreground black} elseif {[winfo class $x] == \"Entry\"} {$x config -state normal\n"
"$x config -foreground black} elseif {[winfo class $x] == \"Button\"} {$x config -state normal} elseif {[winfo class $x] == \"Checkbutton\"} {$x config -state normal} elseif {[winfo class $x] == \"Radiobutton\"} {$x config -state normal} elseif {[winfo class $x] == \"Frame\"} {greyIn $x} elseif {[winfo class $x] == \"Canvas\"} {} elseif {[winfo class $x] == \"Scrollbar\"} {}}\n"
"if { $classi_source != \"file\" } {greyOut $topc.classif.group.file.ent}\n"
"if { $wavecal_arc == 0 } {greyOut $topc.wavecal.group.arc.file}\n"
"return}\n"
"proc blockLabEnt { widget lab ent_size section keyword } {global keyarray\n"
"global found_pos\n"
"global found_val\n"
"global ent_sec\n"
"global ent_key\n"
"set ent_sec($widget.ent) $section\n"
"set ent_key($widget.ent) $keyword\n"
"frame $widget\n"
"label $widget.lab -text $lab\n"
"entry $widget.ent -width $ent_size\n"
"bind $widget.ent <Return> {\n"
"		findInArray $ent_sec(%W) $ent_key(%W)\n"
"        set keyarray($found_pos) [%W get]\n"
"    }\n"
"findInArray $section $keyword\n"
"$widget.ent insert 0 $found_val\n"
"pack $widget.lab -side left\n"
"pack $widget.ent -side right\n"
"return}\n"
"proc displayArray {} {global keyarray\n"
"global currentfile\n"
"global xpos\n"
"global ypos\n"
"global std_entry_size\n"
"global lit_entry_size\n"
"global indent\n"
"global topc\n"
"global spjitter_install\n"
"set xpos 2\n"
"set ypos 2\n"
"set std_entry_size 20\n"
"set lit_entry_size 5\n"
"set indent [expr [winfo screenmmwidth .]/10]\n"
"set array_size [array size keyarray]\n"
"if {$array_size == 0} return\n"
"if { [info exists topc] } {destroy $topc\n"
"destroy .scrolly\n"
"set topc [canvas .canv -yscrollcommand \".scrolly set\"]\n"
"scrollbar .scrolly -orient vertical -command \"$topc yview\"\n"
"pack .scrolly -fill y -side right\n"
"pack $topc -fill both -expand true -side top}\n"
"set line_height 28\n"
"set line_width 600\n"
"if { [winfo exists .launch] } {destroy .launch}\n"
"displayGeneralSection $line_width $line_height\n"
"$topc create line 0 $ypos [winfo screenmmwidth .] $ypos -width 1\n"
"incr ypos\n"
"displayFramesSection $line_width $line_height\n"
"$topc create line 0 $ypos [winfo screenmmwidth .] $ypos -width 1\n"
"incr ypos\n"
"displayCalibrationDataSection $line_width $line_height\n"
"$topc create line 0 $ypos [winfo screenmmwidth .] $ypos -width 1\n"
"incr ypos\n"
"displayClassificationSection $line_width $line_height\n"
"$topc create line 0 $ypos [winfo screenmmwidth .] $ypos -width 1\n"
"incr ypos\n"
"displayWavelengthCalibrationSection $line_width $line_height\n"
"$topc create line 0 $ypos [winfo screenmmwidth .] $ypos -width 1\n"
"incr ypos\n"
"displayDifferencesSection $line_width $line_height\n"
"$topc create line 0 $ypos [winfo screenmmwidth .] $ypos -width 1\n"
"incr ypos\n"
"displayDistortionSection $line_width $line_height\n"
"$topc create line 0 $ypos [winfo screenmmwidth .] $ypos -width 1\n"
"incr ypos\n"
"displayCombinationSection $line_width $line_height\n"
"$topc create line 0 $ypos [winfo screenmmwidth .] $ypos -width 1\n"
"incr ypos\n"
"displaySpectrumExtractionSection $line_width $line_height\n"
"$topc create line 0 $ypos [winfo screenmmwidth .] $ypos -width 1\n"
"incr ypos\n"
"displayOutputSection $line_width $line_height\n"
"$topc config -scrollregion \"0 0 [winfo reqwidth $topc.comb] $ypos\" -width [winfo reqwidth $topc.comb]\n"
"button .launch -text \"Save and launch spjitter with this config\" -background grey70 -command {\n"
"            if { $spjitter_install == 0 } {\n"
"                errorMessage \"Cannot execute spjitter\"\n"
"                return\n"
"            }\n"
"            saveFile\n"
"            wm iconify .\n"
"            toplevel .waitwin\n"
"            label .waitwin.t -text \"spjitter is running - please wait ... \"\n"
"            pack .waitwin.t -side top\n"
"            tkwait visibility .waitwin.t\n"
"            catch {exec spjitter -f $currentfile >&@ stdout}\n"
"            destroy .waitwin\n"
"            wm deiconify .\n"
"        }\n"
"pack .launch -side bottom -fill x\n"
"modFont fixed .\n"
"return}\n"
"proc displayGeneralSection { line_width line_height } {global topc\n"
"global keyarray\n"
"global currentfile\n"
"global xpos\n"
"global ypos\n"
"global found_val\n"
"global found_pos\n"
"global indent\n"
"global inst_type\n"
"frame $topc.g -height [expr 4*$line_height] -width $line_width\n"
"$topc create window $xpos $ypos -window $topc.g -anchor nw\n"
"incr ypos [winfo reqheight $topc.g]\n"
"label $topc.g.lab -text \"General -\"\n"
"pack $topc.g.lab -side top -anchor nw\n"
"findInArray General Eclipse\n"
"label $topc.g.lab2 -text \"Eclipse version: $found_val\"\n"
"pack $topc.g.lab2 -side top -anchor nw -padx $indent -fill x\n"
"frame $topc.g.inst\n"
"findInArray General Algorithm\n"
"set inst_type $found_val\n"
"radiobutton $topc.g.inst.auto_rbut -text \"auto\" -variable inst_type -value auto -command {\n"
"            findInArray General Algorithm\n"
"            set keyarray($found_pos) \"auto\"\n"
"        }\n"
"pack $topc.g.inst.auto_rbut -side left -anchor nw\n"
"radiobutton $topc.g.inst.nochop_rbut -text \"nochop\" -variable inst_type -value nochop -command {\n"
"            findInArray General Algorithm\n"
"            set keyarray($found_pos) \"nochop\"\n"
"        }\n"
"pack $topc.g.inst.nochop_rbut -side left -anchor nw\n"
"radiobutton $topc.g.inst.chop_rbut -text \"chop\" -variable inst_type -value chop -command {\n"
"            findInArray General Algorithm\n"
"            set keyarray($found_pos) \"chop\"\n"
"        }\n"
"pack $topc.g.inst.chop_rbut -side left -anchor nw\n"
"pack $topc.g.inst -side top -anchor nw -padx $indent -fill x\n"
"button $topc.g.but -text \"Update with the current instrument defaults\" -command {\n"
"            findInArray General Algorithm\n"
"            catch { exec spjitter -g -A $found_val -f default_spjitter.ini}\n"
"            set currentfile \"default_spjitter.ini\"\n"
"            file2Array\n"
"            pack .file_selected\n"
"            displayArray\n"
"    }\n"
"pack $topc.g.but -side top\n"
"return}\n"
"proc displayFramesSection { line_width line_height } {global topc\n"
"global keyarray\n"
"global xpos\n"
"global ypos\n"
"global found_val\n"
"global found_pos\n"
"global std_entry_size\n"
"global ent_sec\n"
"global ent_key\n"
"frame $topc.f -height [expr 2*$line_height] -width $line_width\n"
"$topc create window $xpos $ypos -window $topc.f -anchor nw\n"
"incr ypos [winfo reqheight $topc.f]\n"
"frame $topc.f.filelist\n"
"label $topc.f.filelist.lab1 -text \"Frames -\"\n"
"pack $topc.f.filelist.lab1 -side left\n"
"label $topc.f.filelist.lab2 -text \"FileList\"\n"
"pack $topc.f.filelist.lab2 -side left\n"
"entry $topc.f.filelist.ent -width $std_entry_size\n"
"bind $topc.f.filelist.ent <Return> {\n"
"        findInArray Frames FileList\n"
"        set keyarray($found_pos) [$topc.f.filelist.ent get]\n"
"    }\n"
"findInArray Frames FileList\n"
"$topc.f.filelist.ent insert 0 $found_val\n"
"set ent_sec($topc.f.filelist.ent) \"Frames\"\n"
"set ent_key($topc.f.filelist.ent) \"FileList\"\n"
"pack $topc.f.filelist.ent -side left\n"
"button $topc.f.filelist.but -text View -command {\n"
"        roWin \"List of frames\" [$topc.f.filelist.ent get]\n"
"    }\n"
"pack $topc.f.filelist.but -side left\n"
"pack $topc.f.filelist -side top -anchor nw -fill x\n"
"return}\n"
"proc displayCalibrationDataSection { line_width line_height } {global topc\n"
"global xpos\n"
"global ypos\n"
"global found_val\n"
"global std_entry_size\n"
"global last_valid_arc\n"
"global last_valid_sttr\n"
"global last_valid_flat\n"
"global arc_corr\n"
"global sttr_corr\n"
"global flat_div\n"
"frame $topc.calda -height [expr 3*$line_height] -width $line_width\n"
"$topc create window $xpos $ypos -window $topc.calda -anchor nw\n"
"incr ypos [winfo reqheight $topc.calda]\n"
"frame $topc.calda.a\n"
"set last_valid_arc \"none\"\n"
"findInArray CalibrationData ArcTable\n"
"if { $found_val == \"none\" } {set arc_corr 0} else {set arc_corr 1}\n"
"checkbutton $topc.calda.a.cbut -text \"Arc correct. -\" -variable arc_corr -command {\n"
"            findInArray CalibrationData ArcTable\n"
"            if { $arc_corr == 0 } {\n"
"                set last_valid_arc [$topc.calda.a.file.ent get]\n"
"                $topc.calda.a.file.ent delete 0 end\n"
"                $topc.calda.a.file.ent insert 0 \"none\"\n"
"                greyOut $topc.calda.a.file\n"
"            } else {\n"
"                greyIn $topc.calda.a.file\n"
"                $topc.calda.a.file.ent delete 0 end\n"
"                $topc.calda.a.file.ent insert 0 $last_valid_arc\n"
"            }\n"
"        }\n"
"blockLabEnt $topc.calda.a.file \"Filename\" $std_entry_size CalibrationData ArcTable\n"
"pack $topc.calda.a.cbut -side left\n"
"pack $topc.calda.a.file -side right\n"
"if { $arc_corr == 0 } {greyOut $topc.calda.a.file}\n"
"pack $topc.calda.a -side top -anchor nw -fill x\n"
"frame $topc.calda.s\n"
"set last_valid_sttr \"none\"\n"
"findInArray CalibrationData StarTraceTable\n"
"if { $found_val == \"none\" } {set sttr_corr 0} else {set sttr_corr 1}\n"
"checkbutton $topc.calda.s.cbut -text \"Startrace correct. -\" -variable sttr_corr -command {\n"
"            findInArray CalibrationData StarTraceTable\n"
"            if { $sttr_corr == 0 } {\n"
"                set last_valid_sttr [$topc.calda.s.file.ent get]\n"
"                $topc.calda.s.file.ent delete 0 end\n"
"                $topc.calda.s.file.ent insert 0 \"none\"\n"
"                greyOut $topc.calda.s.file\n"
"            } else {\n"
"                greyIn $topc.calda.s.file\n"
"                $topc.calda.s.file.ent delete 0 end\n"
"                $topc.calda.s.file.ent insert 0 $last_valid_sttr\n"
"            }\n"
"        }\n"
"blockLabEnt $topc.calda.s.file \"Filename\" $std_entry_size CalibrationData StarTraceTable\n"
"pack $topc.calda.s.cbut -side left\n"
"pack $topc.calda.s.file -side right\n"
"if { $sttr_corr == 0 } {greyOut $topc.calda.s.file}\n"
"pack $topc.calda.s -side top -anchor nw -fill x\n"
"frame $topc.calda.f\n"
"set last_valid_flat \"none\"\n"
"findInArray CalibrationData MasterSpFlat\n"
"if { $found_val == \"none\" } {set flat_div 0} else {set flat_div 1}\n"
"checkbutton $topc.calda.f.cbut -text \"Flat-field divide -\" -variable flat_div -command {\n"
"            findInArray CalibrationData MasterSpFlat\n"
"            if { $flat_div == 0 } {\n"
"                set last_valid_flat [$topc.calda.f.file.ent get]\n"
"                $topc.calda.f.file.ent delete 0 end\n"
"                $topc.calda.f.file.ent insert 0 \"none\"\n"
"                greyOut $topc.calda.f.file\n"
"            } else {\n"
"                greyIn $topc.calda.f.file\n"
"                $topc.calda.f.file.ent delete 0 end\n"
"                $topc.calda.f.file.ent insert 0 $last_valid_flat\n"
"            }\n"
"        }\n"
"blockLabEnt $topc.calda.f.file \"Filename\" $std_entry_size CalibrationData MasterSpFlat\n"
"pack $topc.calda.f.cbut -side left\n"
"pack $topc.calda.f.file -side right\n"
"if { $flat_div == 0 } {greyOut $topc.calda.f.file}\n"
"pack $topc.calda.f -side top -anchor nw -fill x\n"
"return}\n"
"proc displayClassificationSection { line_width line_height } {global topc\n"
"global xpos\n"
"global ypos\n"
"global found_val\n"
"global found_pos\n"
"global std_entry_size\n"
"global indent\n"
"global classi_source\n"
"frame $topc.classif -height [expr 3*$line_height] -width $line_width\n"
"$topc create window $xpos $ypos -window $topc.classif -anchor nw\n"
"incr ypos [winfo reqheight $topc.classif]\n"
"label $topc.classif.lab -text \"Classification section\"\n"
"pack $topc.classif.lab -side top -anchor nw\n"
"frame $topc.classif.group\n"
"findInArray Classification Select\n"
"set classi_source $found_val\n"
"radiobutton $topc.classif.group.rbut_head -text \"Header\" -variable classi_source -value header -command {\n"
"			findInArray Classification Select\n"
"			set keyarray($found_pos) \"header\"\n"
"			greyOut $topc.classif.group.file.ent\n"
"		}\n"
"pack $topc.classif.group.rbut_head -side top -anchor nw\n"
"frame $topc.classif.group.file\n"
"radiobutton $topc.classif.group.file.rbut_file -text \"File -\" -variable classi_source -value file -command {\n"
"			findInArray Classification Select\n"
"			set keyarray($found_pos) \"file\"\n"
"			greyIn $topc.classif.group.file.ent\n"
"		}\n"
"pack $topc.classif.group.file.rbut_file -side left\n"
"blockLabEnt $topc.classif.group.file.ent \"Offsets file\" $std_entry_size Classification OffsetFile\n"
"pack $topc.classif.group.file.ent -side right\n"
"if { $classi_source != \"file\" } {greyOut $topc.classif.group.file.ent}\n"
"pack $topc.classif.group.file -side top -anchor nw\n"
"pack $topc.classif.group -side top -anchor nw -padx $indent -fill x\n"
"return}\n"
"proc displayWavelengthCalibrationSection { line_width line_height } {global topc\n"
"global xpos\n"
"global ypos\n"
"global found_val\n"
"global found_pos\n"
"global std_entry_size\n"
"global lit_entry_size\n"
"global indent\n"
"global wavecal_sel\n"
"global wavecal_arc\n"
"frame $topc.wavecal -height [expr 6*$line_height] -width $line_width\n"
"$topc create window $xpos $ypos -window $topc.wavecal -anchor nw\n"
"incr ypos [winfo reqheight $topc.wavecal]\n"
"findInArray WavelengthCalibration Select\n"
"if { $found_val == \"yes\" } {set wavecal_sel 1} else {set wavecal_sel 0}\n"
"checkbutton $topc.wavecal.cbut -text \"Wavelength calibration\" -variable wavecal_sel -command {\n"
"			findInArray WavelengthCalibration Select\n"
"			if { $wavecal_sel == 0 } {\n"
"				set keyarray($found_pos) \"no\"\n"
"				greyOut $topc.wavecal.group\n"
"			} else {\n"
"				set keyarray($found_pos) \"yes\"\n"
"				greyIn $topc.wavecal.group\n"
"			}\n"
"		}\n"
"pack $topc.wavecal.cbut -side top -anchor nw\n"
"frame $topc.wavecal.group\n"
"frame $topc.wavecal.group.arc\n"
"findInArray WavelengthCalibration WavecalArcFile\n"
"if { $found_val == \"none\" } {set wavecal_arc 0} else {set wavecal_arc 1}\n"
"checkbutton $topc.wavecal.group.arc.cbut -text \"Arc file -\" -variable wavecal_arc -command { \n"
"			findInArray WavelengthCalibration WavecalArcFile\n"
"			if { $wavecal_arc == 0 } {\n"
"				set keyarray($found_pos) \"no\"\n"
"				greyOut $topc.wavecal.group.arc.file\n"
"			} else {\n"
"				set keyarray($found_pos) \"yes\"\n"
"				greyIn $topc.wavecal.group.arc.file\n"
"			}\n"
"		}\n"
"blockLabEnt $topc.wavecal.group.arc.file \"Filename\" $std_entry_size WavelengthCalibration WavecalArcFile\n"
"pack $topc.wavecal.group.arc.cbut -side left\n"
"pack $topc.wavecal.group.arc.file -side right\n"
"if { $wavecal_arc == 0 } {greyOut $topc.wavecal.group.arc.file}\n"
"pack $topc.wavecal.group.arc -side top -anchor nw -fill x\n"
"blockLabEnt $topc.wavecal.group.dishi \"DiscardHigh\" $lit_entry_size WavelengthCalibration DiscardHigh\n"
"pack $topc.wavecal.group.dishi -side top -anchor nw -fill x\n"
"blockLabEnt $topc.wavecal.group.dislo \"DiscardLow\" $lit_entry_size WavelengthCalibration DiscardLow\n"
"pack $topc.wavecal.group.dislo -side top -anchor nw -fill x\n"
"blockLabEnt $topc.wavecal.group.disle \"DiscardLeft\" $lit_entry_size WavelengthCalibration DiscardLeft\n"
"pack $topc.wavecal.group.disle -side top -anchor nw -fill x\n"
"blockLabEnt $topc.wavecal.group.disri \"DiscardRight\" $lit_entry_size WavelengthCalibration DiscardRight\n"
"pack $topc.wavecal.group.disri -side top -anchor nw -fill x\n"
"blockLabEnt $topc.wavecal.group.nbcoeff \"Nb coeffs\" $lit_entry_size WavelengthCalibration WavecalNbCoeff\n"
"pack $topc.wavecal.group.nbcoeff -side top -anchor nw -fill x\n"
"pack $topc.wavecal.group -side top -anchor nw -padx $indent\n"
"if { $wavecal_sel == 0 } {greyOut $topc.wavecal.group}\n"
"return}\n"
"proc displayDifferencesSection { line_width line_height } {global topc\n"
"global xpos\n"
"global ypos\n"
"global found_val\n"
"global found_pos\n"
"global indent\n"
"global diff_method\n"
"frame $topc.diff -height [expr 2*$line_height] -width $line_width\n"
"$topc create window $xpos $ypos -window $topc.diff -anchor nw\n"
"incr ypos [winfo reqheight $topc.diff]\n"
"label $topc.diff.lab -text \"Differences section\"\n"
"pack $topc.diff.lab -side top -anchor nw\n"
"findInArray Differences Method\n"
"set diff_method $found_val\n"
"radiobutton $topc.diff.rbut_all -text \"All\" -variable diff_method -value all -command {\n"
"			findInArray Differences Method\n"
"			set keyarray($found_pos) \"all\"\n"
"		}\n"
"pack $topc.diff.rbut_all -side left -anchor nw\n"
"radiobutton $topc.diff.rbut_half -text \"Half\" -variable diff_method -value half -command {\n"
"			findInArray Differences Method\n"
"			set keyarray($found_pos) \"half\"\n"
"		}\n"
"pack $topc.diff.rbut_half -side left -anchor nw\n"
"return}\n"
"proc displayDistortionSection { line_width line_height } {global topc\n"
"global xpos\n"
"global ypos\n"
"global found_val\n"
"global found_pos\n"
"global lit_entry_size\n"
"global indent\n"
"global dist_sel\n"
"global autodark\n"
"frame $topc.dist -height [expr 6*$line_height] -width $line_width\n"
"$topc create window $xpos $ypos -window $topc.dist -anchor nw\n"
"incr ypos [winfo reqheight $topc.dist]\n"
"findInArray Distortion Select\n"
"if { $found_val == \"yes\" } {set dist_sel 1} else {set dist_sel 0}\n"
"checkbutton $topc.dist.cbut -text \"Distortion correction\" -variable dist_sel -command {\n"
"			findInArray Distortion Select\n"
"			if { $dist_sel == 0 } {\n"
"				set keyarray($found_pos) \"no\"\n"
"				greyOut $topc.dist.group\n"
"			} else {\n"
"				set keyarray($found_pos) \"yes\"\n"
"				greyIn $topc.dist.group\n"
"			}\n"
"		}\n"
"pack $topc.dist.cbut -side top -anchor nw\n"
"frame $topc.dist.group\n"
"findInArray Distortion AutoDarkSubtraction\n"
"if { $found_val == \"no\" } {set autodark 0} else {set autodark 1}\n"
"checkbutton $topc.dist.group.cbut -text \"Auto dark subtraction\" -variable autodark -command {\n"
"            findInArray Distortion AutoDarkSubtraction \n"
"            if { $autodark == 0 } {\n"
"                set keyarray($found_pos) \"no\"\n"
"            } else {\n"
"                set keyarray($found_pos) \"yes\"\n"
"            }\n"
"        }\n"
"pack $topc.dist.group.cbut -side top -anchor nw -fill x\n"
"blockLabEnt $topc.dist.group.xmin \"XMin\" $lit_entry_size Distortion XMin\n"
"pack $topc.dist.group.xmin -side top -anchor nw -fill x\n"
"blockLabEnt $topc.dist.group.ymin \"YMin\" $lit_entry_size Distortion YMin\n"
"pack $topc.dist.group.ymin -side top -anchor nw -fill x\n"
"blockLabEnt $topc.dist.group.xmax \"XMax\" $lit_entry_size Distortion XMax\n"
"pack $topc.dist.group.xmax -side top -anchor nw -fill x\n"
"blockLabEnt $topc.dist.group.ymax \"YMax\" $lit_entry_size Distortion YMax\n"
"pack $topc.dist.group.ymax -side top -anchor nw -fill x\n"
"pack $topc.dist.group -side top -anchor nw -padx $indent\n"
"if { $dist_sel == 0 } {greyOut $topc.dist.group}\n"
"return}\n"
"proc displayCombinationSection { line_width line_height } {global topc\n"
"global xpos\n"
"global ypos\n"
"global found_val\n"
"global found_pos\n"
"global lit_entry_size\n"
"global indent\n"
"global circ_shift\n"
"global refine_offsets\n"
"global comb_meth\n"
"frame $topc.comb -height [expr 8*$line_height] -width $line_width\n"
"$topc create window $xpos $ypos -window $topc.comb -anchor nw\n"
"incr ypos [winfo reqheight $topc.comb]\n"
"label $topc.comb.lab -text \"Combination section\"\n"
"pack $topc.comb.lab -side top -anchor nw\n"
"findInArray Combination CircularShift\n"
"if { $found_val == \"no\" } {set circ_shift 0} else {set circ_shift 1}\n"
"checkbutton $topc.comb.cshift -text \"Use circular shift\" -variable circ_shift -command {\n"
"            findInArray Combination CircularShift\n"
"            if { $circ_shift == 0 } {\n"
"                set keyarray($found_pos) \"no\"\n"
"            } else {\n"
"                set keyarray($found_pos) \"yes\"\n"
"            }\n"
"        }\n"
"pack $topc.comb.cshift -side top -anchor nw -padx $indent\n"
"findInArray Combination RefineOffsets\n"
"if { $found_val == \"no\" } {set refine_offsets 0} else {set refine_offsets 1}\n"
"checkbutton $topc.comb.refine -text \"Refine offsets\" -variable refine_offsets -command {\n"
"            findInArray Combination RefineOffsets\n"
"            if { $refine_offsets == 0 } {\n"
"                set keyarray($found_pos) \"no\"\n"
"            } else {\n"
"                set keyarray($found_pos) \"yes\"\n"
"            }\n"
"        }\n"
"pack $topc.comb.refine -side top -anchor nw -padx $indent\n"
"label $topc.comb.lab2 -text \"Combination method\"\n"
"pack $topc.comb.lab2 -side top -anchor nw -padx $indent\n"
"frame $topc.comb.method\n"
"findInArray Combination Method\n"
"set comb_meth $found_val\n"
"radiobutton $topc.comb.method.med_rbut -text \"Median\" -variable comb_meth -value \"median\" -command {\n"
"			findInArray Combination Method\n"
"			set keyarray($found_pos) \"median\"\n"
"			greyOut $topc.comb.method.rej\n"
"		}\n"
"pack $topc.comb.method.med_rbut -side top -anchor nw -padx $indent\n"
"radiobutton $topc.comb.method.rej_rbut -text \"Rejection\" -variable comb_meth -value \"rejection\" -command {\n"
"            findInArray Combination Method \n"
"            set keyarray($found_pos) \"rejection\"\n"
"            greyIn $topc.comb.method.rej\n"
"        }\n"
"pack $topc.comb.method.rej_rbut -side top -anchor nw -padx $indent\n"
"frame $topc.comb.method.rej\n"
"blockLabEnt $topc.comb.method.rej.hi \"AverageHiRejection\" $lit_entry_size Combination AverageHiRejection\n"
"pack $topc.comb.method.rej.hi -side top -anchor nw -fill x -padx $indent\n"
"blockLabEnt $topc.comb.method.rej.lo \"AverageLoRejection\" $lit_entry_size Combination AverageLoRejection\n"
"pack $topc.comb.method.rej.lo -side top -anchor nw -fill x -padx $indent\n"
"pack $topc.comb.method.rej -side top -anchor nw -padx $indent\n"
"if { $comb_meth != \"rejection\" } {greyOut $topc.comb.method.rej}\n"
"radiobutton $topc.comb.method.lin_rbut -text \"Linear\" -variable comb_meth -value \"linear\" -command {\n"
"            findInArray Combination Method\n"
"            set keyarray($found_pos) \"linear\"\n"
"            greyOut $topc.comb.method.rej\n"
"        }\n"
"pack $topc.comb.method.lin_rbut -side top -anchor nw -padx $indent\n"
"pack $topc.comb.method -side top -anchor nw -fill x -padx $indent\n"
"return}\n"
"proc displaySpectrumExtractionSection { line_width line_height } {global topc\n"
"global xpos\n"
"global ypos\n"
"global found_val\n"
"global found_pos\n"
"global lit_entry_size\n"
"global indent\n"
"global ext_sel\n"
"global apply_filter\n"
"frame $topc.ext -height [expr 11*$line_height] -width $line_width\n"
"$topc create window $xpos $ypos -window $topc.ext -anchor nw\n"
"incr ypos [winfo reqheight $topc.ext]\n"
"findInArray SpectrumExtraction Select\n"
"if { $found_val == \"yes\" } {set ext_sel 1} else {set ext_sel 0}\n"
"checkbutton $topc.ext.cbut -text \"Extract the spectrum\" -variable ext_sel -command {\n"
"			findInArray SpectrumExtraction Select\n"
"			if { $ext_sel == 0 } {\n"
"				set keyarray($found_pos) \"no\"\n"
"				greyOut $topc.ext.group\n"
"			} else {\n"
"				set keyarray($found_pos) \"yes\"\n"
"				greyIn $topc.ext.group\n"
"			}\n"
"		}\n"
"pack $topc.ext.cbut -side top -anchor nw\n"
"frame $topc.ext.group\n"
"blockLabEnt $topc.ext.group.specw \"SpectrumWidth\" $lit_entry_size SpectrumExtraction SpectrumWidth\n"
"pack $topc.ext.group.specw -side top -anchor nw -fill x\n"
"blockLabEnt $topc.ext.group.badtop \"BadTop\" $lit_entry_size SpectrumExtraction BadTop\n"
"pack $topc.ext.group.badtop -side top -anchor nw -fill x\n"
"blockLabEnt $topc.ext.group.badleft \"BadLeft\" $lit_entry_size SpectrumExtraction BadLeft\n"
"pack $topc.ext.group.badleft -side top -anchor nw -fill x\n"
"blockLabEnt $topc.ext.group.badright \"BadTop\" $lit_entry_size SpectrumExtraction BadRight\n"
"pack $topc.ext.group.badright -side top -anchor nw -fill x\n"
"blockLabEnt $topc.ext.group.badbot \"BadBot\" $lit_entry_size SpectrumExtraction BadBot\n"
"pack $topc.ext.group.badbot -side top -anchor nw -fill x\n"
"blockLabEnt $topc.ext.group.skyhw \"ResSkyHiWidth\" $lit_entry_size SpectrumExtraction ResSkyHiWidth\n"
"pack $topc.ext.group.skyhw -side top -anchor nw -fill x\n"
"blockLabEnt $topc.ext.group.skyhd \"ResSkyHiDist\" $lit_entry_size SpectrumExtraction ResSkyHiDist\n"
"pack $topc.ext.group.skyhd -side top -anchor nw -fill x\n"
"blockLabEnt $topc.ext.group.skylw \"ResSkyLoWidth\" $lit_entry_size SpectrumExtraction ResSkyLoWidth\n"
"pack $topc.ext.group.skylw -side top -anchor nw -fill x\n"
"blockLabEnt $topc.ext.group.skyld \"ResSkyLoDist\" $lit_entry_size SpectrumExtraction ResSkyLoDist\n"
"pack $topc.ext.group.skyld -side top -anchor nw -fill x\n"
"findInArray SpectrumExtraction ApplyFilter\n"
"if { $found_val == \"yes\" } {set apply_filter 1} else {set apply_filter 0}\n"
"checkbutton $topc.ext.group.cbut -text \"Apply filter\" -variable apply_filter -command {\n"
"			findInArray SpectrumExtraction ApplyFilter\n"
"			if { $apply_filter == 0 } {\n"
"				set keyarray($found_pos) \"no\"\n"
"			} else {\n"
"				set keyarray($found_pos) \"yes\"\n"
"			}	\n"
"		}\n"
"pack $topc.ext.group.cbut -side top -anchor nw\n"
"blockLabEnt $topc.ext.group.specpos \"SpectrumPosition\" $lit_entry_size SpectrumExtraction SpectrumPosition\n"
"pack $topc.ext.group.specpos -side top -anchor nw -fill x\n"
"pack $topc.ext.group -side top -anchor nw -fill x -padx $indent\n"
"return}\n"
"proc displayOutputSection { line_width line_height } {global topc\n"
"global xpos\n"
"global ypos\n"
"global found_val\n"
"global found_pos\n"
"global std_entry_size\n"
"global indent\n"
"global stat_rep\n"
"global plot\n"
"global viewer\n"
"frame $topc.out -height [expr 5*$line_height] -width $line_width\n"
"$topc create window $xpos $ypos -window $topc.out -anchor nw\n"
"incr ypos [winfo reqheight $topc.out]\n"
"label $topc.out.label -text \"Output section\"\n"
"pack $topc.out.label -side top -anchor nw\n"
"blockLabEnt $topc.out.outfile \"Output file\" $std_entry_size Output BaseName\n"
"pack $topc.out.outfile -side top -anchor nw -fill x -padx $indent\n"
"findInArray Output ProduceStatusReport\n"
"if { $found_val == \"yes\" } {set stat_rep 1} else {set stat_rep 0}\n"
"checkbutton $topc.out.rep_cbut -text \"Produce status report\" -variable stat_rep -command {\n"
"			findInArray Output ProduceStatusReport \n"
"			if { $stat_rep == 0 } {\n"
"				set keyarray($found_pos) \"no\"\n"
"			} else {\n"
"				set keyarray($found_pos) \"yes\"\n"
"			}\n"
"		}\n"
"pack $topc.out.rep_cbut -side top -anchor nw -padx $indent\n"
"findInArray Output PlotSpectrum\n"
"if { $found_val == \"yes\" } {set plot 1} else {set plot 0}\n"
"checkbutton $topc.out.plot -text \"Plot spectrum\" -variable plot -command {\n"
"			findInArray Output PlotSpectrum\n"
"			if { $plot == 0 } {\n"
"				set keyarray($found_pos) \"no\"\n"
"			} else {\n"
"				set keyarray($found_pos) \"yes\"\n"
"			}\n"
"		}\n"
"pack $topc.out.plot -side top -anchor nw -padx $indent\n"
"frame $topc.out.start\n"
"findInArray Output StartViewer\n"
"if { $found_val == \"yes\" } {set viewer 1} else {set viewer 0}\n"
"checkbutton $topc.out.start.cbut -text \"Start viewer -\" -variable viewer -command {\n"
"            findInArray Output StartViewer\n"
"            if { $viewer == 0 } {\n"
"                set keyarray($found_pos) \"no\"\n"
"                greyOut $topc.out.start.command\n"
"            } else {\n"
"                set keyarray($found_pos) \"yes\"\n"
"                greyIn $topc.out.start.command\n"
"            }\n"
"        }\n"
"blockLabEnt $topc.out.start.command \"command\" $std_entry_size Output StartCommand\n"
"pack $topc.out.start.cbut -side left\n"
"pack $topc.out.start.command -side top -anchor nw\n"
"if { $viewer == 0 } {greyOut $topc.out.start.command}\n"
"pack $topc.out.start -side top -anchor nw -fill x -padx $indent\n"
"return}\n"
"proc saveFile {} {global keyarray\n"
"global currentfile\n"
"if { [array size keyarray] == 0 } {errorMessage \"No data to save\"\n"
"return}\n"
"if { $currentfile == \"No name\" } {errorMessage \"No file name specified\"\n"
"return}\n"
"updateEntries .\n"
"if [catch {open $currentfile w} fileId] {errorMessage \"Cannot open file $currentfile\"} else {set i 0\n"
"set j 1\n"
"set k 2\n"
"set array_size [array size keyarray]\n"
"set section $keyarray($i)\n"
"puts $fileId \"\\[$section\\]\"\n"
"puts $fileId \"$keyarray($j) = $keyarray($k)\"\n"
"while {$k<[expr $array_size-3]} {incr i 3\n"
"incr j 3\n"
"incr k 3\n"
"if {$section == $keyarray($i)} {puts $fileId \"$keyarray($j) = $keyarray($k)\"} else {set section $keyarray($i)\n"
"puts $fileId \"\\[$section\\]\"\n"
"puts $fileId \"$keyarray($j) = $keyarray($k)\"}}\n"
"close $fileId}\n"
"return}\n"
"proc openFile {} {global currentfile\n"
"global fileselect\n"
"global keyarray\n"
"catch { fileSelect }\n"
"if {$fileselect(path)==\"\"} return\n"
"set currentfile $fileselect(path)\n"
"pack .file_selected\n"
"file2Array\n"
"displayArray\n"
"return}\n"
"proc newFile {} {global keyarray\n"
"global currentfile\n"
"global spjitter_install\n"
"if { $spjitter_install == 0 } {errorMessage \"Cannot execute spjitter -g\"\n"
"return}\n"
"catch { exec spjitter -g }\n"
"set currentfile \"spjitter.ini\"\n"
"file2Array\n"
"pack .file_selected\n"
"displayArray\n"
"return}\n"
"proc saveAsFile {} {global currentfile\n"
"global keyarray\n"
"global fileselect\n"
"global cont\n"
"catch { fileSelect \"File entry\" {} 0 }\n"
"if {$fileselect(path)==\"\"} return\n"
"if {[file exists $fileselect(path)]} {set cnf [toplevel .confirm]\n"
"wm title $cnf \"Confirmation\"\n"
"frame $cnf.que -width 500 -background white -borderwidth 5 -cursor hand2 -relief ridge\n"
"message $cnf.que.msg -width 500 -background black -borderwidth 5 -cursor hand2 -font 9x15bold -foreground white -justify center -relief ridge -text \"Do you want to overwrite the file $fileselect(path)?\"\n"
"button $cnf.que.ok -activebackground red -activeforeground black -background blue -borderwidth 5 -command \"set cont 1\" -font 8x13bold -foreground cyan -relief groove -text Yes\n"
"button $cnf.que.no -activebackground red -activeforeground black -background blue -borderwidth 5 -command \"set cont 0\" -font 8x13bold -foreground cyan -relief groove -text No\n"
"pack $cnf.que -side top -fill x\n"
"pack $cnf.que.msg\n"
"pack $cnf.que.ok -side left\n"
"pack $cnf.que.no -side right\n"
"tkwait variable cont\n"
"if {$cont} {destroy $cnf} else {destroy $cnf\n"
"return}}\n"
"if { [array size keyarray] == 0 } {errorMessage \"No data to save\"\n"
"return}\n"
"set currentfile $fileselect(path)\n"
"pack .file_selected\n"
"saveFile\n"
"return}\n"
"proc fileselectResources {} {option add *Fileselect*path.relief sunken startup\n"
"option add *Fileselect*path.background white startup\n"
"option add *Fileselect*path.foreground black startup\n"
"option add *Fileselect*l.text File: startup\n"
"option add *Fileselect*ok*text OK startup\n"
"option add *Fileselect*ok*underline 0 startup\n"
"option add *Fileselect*cancel.text Cancel startup\n"
"option add *Fileselect*cancel.underline 0 startup\n"
"option add *Fileselect*list.width 20 startup\n"
"option add *Fileselect*list.height 10 startup}\n"
"proc fileSelect {{why \"File Selection\"} {default {}} {mustExist 1} } {global fileselect\n"
"set t [toplevel .fileselect -bd 4 -class Fileselect]\n"
"fileselectResources\n"
"message $t.msg -aspect 1000 -text $why\n"
"pack $t.msg -side top -fill x\n"
"set fileselect(dirEnt) [entry $t.dir -width 15 -relief flat -state disabled]\n"
"pack $t.dir -side top -fill x\n"
"frame $t.top\n"
"label $t.top.l -padx 0\n"
"set e [entry $t.top.path -textvariable fileselect(path)]\n"
"pack $t.top -side top -fill x\n"
"pack $t.top.l -side left\n"
"pack $t.top.path -side right -fill x -expand true\n"
"set lb [listbox $t.list -yscrollcommand [list $t.scroll set]]\n"
"scrollbar $t.scroll -command [list $lb yview]\n"
"frame $t.buttons -bd 10\n"
"frame $t.buttons.ok -bd 2 -relief sunken\n"
"set ok [button $t.buttons.ok.b -command fileselectOK]\n"
"set can [button $t.buttons.cancel -command fileselectCancel]\n"
"pack $t.list -side left -fill both -expand true\n"
"pack $t.scroll -side left -fill y\n"
"pack $t.buttons -side left -fill both\n"
"pack $t.buttons.ok $t.buttons.cancel -side top -padx 10 -pady 5\n"
"pack $t.buttons.ok.b -padx 4 -pady 4\n"
"fileselectBindings $t $e $lb $ok $can\n"
"if {[string length $default] == 0} {set fileselect(path) {}\n"
"set dir [pwd]} else {set fileselect(path) [file tail $default]\n"
"set dir [file dirname $default]}\n"
"set fileselect(dir) {}\n"
"set fileselect(done) 0\n"
"set fileselect(mustExist) $mustExist\n"
"tkwait visibility .fileselect.list\n"
"fileselectList $dir\n"
"tkwait variable fileselect(done)\n"
"destroy $t\n"
"return $fileselect(path)}\n"
"proc fileselectBindings { t e lb ok can } {foreach w [list $e $lb $ok $can] {bindtags $w [list $t [winfo class $w] $w]}\n"
"bind $t <Control-c> fileselectCancel\n"
"bind $e <Return> fileselectOK\n"
"bind $e <space> fileselectComplete\n"
"bind $lb <space> \"fileselectTake $%W ; focus $e\"\n"
"bind $lb <Button-1> \"fileselectClick %W %y ; focus $e\"\n"
"bind $lb <Return> \"fileselectTake %W ; fileselectOK\"\n"
"bind $lb <Double-Button-1> \"fileselectClick %W %y ; fileselectOK\"\n"
"bind $e <Tab> \"focus $lb ; $lb select set 0\"\n"
"bind $lb <Tab> \"focus $e\"\n"
"foreach but [list $ok $can] {set char [string tolower [string index [$but cget -text] [$but cget -underline]]]\n"
"bind $t <Alt-$char> \"focus $but ; break\"}\n"
"bind $ok <Tab> \"focus $can\"\n"
"bind $can <Tab> \"focus $ok\"\n"
"focus $e}\n"
"proc fileselectList { dir {files {}} } {global fileselect\n"
"set e $fileselect(dirEnt)\n"
"$e config -state normal\n"
"$e delete 0 end\n"
"$e insert 0 $dir\n"
"$e config -state disabled\n"
"$e xview moveto 1\n"
".fileselect.list delete 0 end\n"
"set fileselect(dir) $dir\n"
"if ![file isdirectory $dir] {.fileselect.list insert 0 \"Bad Directory\"\n"
"return}\n"
".fileselect.list insert 0 Listing...\n"
"update idletasks\n"
".fileselect.list delete 0\n"
"if {[string length $files] == 0} {set err [catch {set files [glob -nocomplain $fileselect(dir)/*]}]\n"
".fileselect.list insert end ../}\n"
"set dirs {}\n"
"set others {}\n"
"foreach f [lsort $files] {if [file isdirectory $f] {lappend dirs [file tail $f]/} else {lappend others [file tail $f]}}\n"
"foreach f [concat $dirs $others] {.fileselect.list insert end $f}}\n"
"proc fileselectOK {} {global fileselect\n"
"if {[regsub {^\\.\\./?} $fileselect(path) {} newpath] != 0} {set fileselect(path) $newpath\n"
"set fileselect(dir) [file dirname $fileselect(dir)]\n"
"fileselectOK\n"
"return}\n"
"set path [string trimright $fileselect(dir)/$fileselect(path) /]\n"
"if [file isdirectory $path] {set fileselect(path) {}\n"
"fileselectList $path\n"
"return}\n"
"if [file exists $path] {set fileselect(path) $path\n"
"set fileselect(done) 1\n"
"return}\n"
"if [catch {glob $path} files] {if [catch {glob $fileselect(path)} path] {if {$fileselect(mustExist)} {fileselectComplete} elseif [file isdirectory [file dirname $fileselect(path)]] {set fileselect(done) 1}\n"
"return} else {set fileselect(dir) [file dirname $fileselect(path)]\n"
"set fileselect(path) [file tail $fileselect(path)]\n"
"fileselectOK\n"
"return}} else {if {[llength [split $files]] == 1} {set fileselect(path) $files\n"
"fileselectOK} else {set fileselect(dir) [file dirname [lindex $files 0]]\n"
"fileselectList $fileselect(dir) $files}}}\n"
"proc fileselectCancel {} {global fileselect\n"
"set fileselect(done) 1\n"
"set fileselect(path) {}}\n"
"proc fileselectClick { lb y } {global fileselect\n"
"set fileselect(path) [$lb get [$lb nearest $y]]}\n"
"proc fileselectTake { lb } {global fileselect\n"
"set fileselect(path) [$lb get [$lb curselection]]}\n"
"proc fileselectComplete {} {global fileselect\n"
"set fileselect(path) [string trim $fileselect(path) \\t\\ ]\n"
"if {[string match /* $fileselect(path)]} {set dir [file dirname $fileselect(path)]\n"
"set tail [file tail $fileselect(path)]} elseif [string match ~* $fileselect(path)] {if [catch {file dirname $fileselect(path)} dir] {return}\n"
"set tail [file tail $fileselect(path)]} else {set path $fileselect(dir)/$fileselect(path)\n"
"set dir [file dirname $path]\n"
"set tail [file tail $path]}\n"
"set files [glob -nocomplain $dir/$tail*]\n"
"if {[llength [split $files]] == 1} {set fileselect(dir) $dir\n"
"set fileselect(path) [file tail $files]} else {if {[llength [split $files]] > 1} {set l [expr [string length $tail]-1]\n"
"set miss 0\n"
"set file1 [file tail [lindex $files 0]]\n"
"while {!$miss} {incr l\n"
"if {$l == [string length $file1]} {break}\n"
"set new [string range $file1 0 $l]\n"
"foreach f $files {if ![string match $new* [file tail $f]] {set miss 1\n"
"incr l -1\n"
"break}}}\n"
"set fileselect(path) [string range $file1 0 $l]}\n"
"fileselectList $dir $files}}\n"
"proc file2Array {} {global keyarray\n"
"global currentfile\n"
"set i 0\n"
"if {[array exists keyarray]} {unset keyarray}\n"
"if [catch {open $currentfile r} fileId] {errorMessage \"Cannot open file $currentfile\"} else {set section \"Unknown section\"\n"
"while {![eof $fileId]} {gets $fileId curr_line\n"
"if {[regsub {^\\[[A-Z][a-zA-Z]*\\]} $curr_line {&} section_line]} {regsub {\\[} $section_line {} section\n"
"regsub {\\]} $section {} section}\n"
"if {[regsub {^[A-Z][A-Za-z]*} $curr_line {&} keyword_line]} {if {![regsub {=.*} $keyword_line {} keyword]} {errorMessage \"Sign = missing after a keyword in INI file.\"} else {regsub {( )*$} $keyword {} keyword\n"
"regsub {;.*} $keyword_line {} value_line\n"
"regsub {.*= } $value_line {} value\n"
"regsub {( )*$} $value {} value\n"
"regsub {^( |\\t)*} $value {} value\n"
"set keyarray($i) $section\n"
"incr i\n"
"set keyarray($i) $keyword\n"
"incr i\n"
"set keyarray($i) $value\n"
"incr i}}}\n"
"close $fileId\n"
"if {[array size keyarray] == 6} {errorMessage \"No INI data in the file $currentfile\"}}\n"
"return}\n"
"proc ini2Help { inifile helpfile } {if [catch {open $inifile r} fileId] {errorMessage \"Cannot open file $inifile\"} else {if [catch {open $helpfile w} fileId2] {errorMessage \"Cannot open file $helpfile\"} else {while {![eof $fileId]} {gets $fileId curr_line\n"
"if {[regsub {^\\#} $curr_line {} help_line]} {puts $fileId2 $help_line}}}\n"
"close $fileId\n"
"close $fileId2}\n"
"return}\n"
"proc findInArray { section keyword } {global keyarray\n"
"global found_val\n"
"global found_pos\n"
"set found_val 0\n"
"set found_pos 0\n"
"set array_size [array size keyarray]\n"
"set i 0\n"
"set j 1\n"
"set k 2\n"
"while {$k<$array_size} {if {($keyarray($i) == $section) && ($keyarray($j) == $keyword)} {set found_pos $k\n"
"set found_val $keyarray($k)\n"
"return}\n"
"incr i 3\n"
"incr j 3\n"
"incr k 3}\n"
"if {$section != \"General\"} {errorMessage \"Value of \\[$section\\], $keyword not found in the array\"}\n"
"set found_pos -1\n"
"set found_val -1\n"
"return}\n"
"proc updateEntries { widget } {global keyarray\n"
"global found_pos\n"
"global ent_sec\n"
"global ent_key\n"
"global topc\n"
"set children [winfo children $widget]\n"
"foreach x $children {if { ([winfo class $x] == \"Entry\") } {findInArray $ent_sec($x) $ent_key($x)\n"
"set keyarray($found_pos) [$x get]} else {updateEntries $x}}\n"
"return}\n"
"\n";

/*-----------------------------------------------------------------------------
  							Function codes
 -----------------------------------------------------------------------------*/
int spjitter_gui()
{
    FILE    *   wish ;

    if ((wish=popen("wish", "w"))==NULL) {
        printf("cannot run wish?\n");
        return -1 ;
    }
    fprintf(wish, "%s\n", tcl_code);
    fflush(wish);
    pclose(wish);
    return 0 ;
}


