/*-----------------------------------------------------------------------------
   
   File name    :   jgui.c
   Author       :   Y. Jung
   Created on   :   June 2001
   Description  :   Graphical user interface for the jitter

 -----------------------------------------------------------------------------*/

/*
    $Id: jgui.c,v 1.8 2002/12/05 10:09:45 yjung Exp $
    $Author: yjung $
    $Date: 2002/12/05 10:09:45 $
    $Revision: 1.8 $
*/

/*----------------------------------------------------------------------------
                                Includes
 ---------------------------------------------------------------------------*/

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>

/*----------------------------------------------------------------------------
                                Static TCL code
 ---------------------------------------------------------------------------*/
static char tcl_code[] =

"proc errorMessage { string_arg } {global var\n"
"global but_font\n"
"set win [toplevel .window]\n"
"wm title .window \"Error message\"\n"
"frame $win.err -background white -borderwidth 10 -cursor pirate -height 100 -width 60\n"
"label $win.err.lab -background black -borderwidth 5 -font $but_font -foreground white -relief sunken -text $string_arg -width 60 -wraplength 500\n"
"button $win.err.but -activebackground red -activeforeground black -background blue -borderwidth 5 -command \"set var 1\" -font $but_font -foreground white -relief groove -text Ok\n"
"pack $win.err -side top\n"
"pack $win.err.lab -side top\n"
"pack $win.err.but\n"
"tkwait variable var\n"
"destroy $win\n"
"return}\n"
"catch {exec rm tclIndex}\n"
"lappend auto_path [exec dirname [exec which $argv0]]\n"
"proc mainProg {} {global but_act_back_col\n"
"global but_back_col\n"
"global but_fore_col\n"
"global lab_back_col\n"
"global but_font\n"
"global argv\n"
"global argc\n"
"global currentfile\n"
"global topc\n"
"set but_act_back_col cyan3\n"
"set but_back_col cyan2\n"
"set but_fore_col blue\n"
"set lab_back_col SkyBlue1\n"
"set but_font 8x13bold\n"
"set currentfile \"No Name\"\n"
"wm title . \"jitter.ini configuration\"\n"
"frame .mbar -relief raised -background $lab_back_col -borderwidth 2\n"
"menubutton .mbar.file -activebackground $but_act_back_col -activeforeground black -background $but_back_col -font $but_font -foreground $but_fore_col -relief raised -text File -menu .mbar.file.menu\n"
"menu .mbar.file.menu -tearoff 0\n"
".mbar.file.menu add command -label \"Open...\" -command \"openFile\"\n"
".mbar.file.menu add command -label \"New\" -command \"newFile\"\n"
".mbar.file.menu add command -label \"Save\" -command \"saveFile\"\n"
".mbar.file.menu add command -label \"Save as...\" -command \"saveAsFile\"\n"
".mbar.file.menu add separator\n"
".mbar.file.menu add command -label \"Exit\" -command exit\n"
"menubutton .mbar.opti -activebackground $but_act_back_col -activeforeground black -background $but_back_col -font $but_font -foreground $but_fore_col -relief raised -text \"Options\" -menu .mbar.opti.menu\n"
"menu .mbar.opti.menu -tearoff 0\n"
".mbar.opti.menu add cascade -label \"Fonts\" -menu .mbar.opti.menu.fonts\n"
".mbar.opti.menu add cascade -label \"Colors\" -menu .mbar.opti.menu.color\n"
"menu .mbar.opti.menu.fonts -tearoff 0\n"
".mbar.opti.menu.fonts add command -label \"Fixed\" -command \"modFont fixed .\"\n"
".mbar.opti.menu.fonts add command -label \"Helvetica\" -command {\n"
"		if {[catch {modFont -*-helvetica-medium-r-normal-*-14-*-*-*-*-*-iso8859-* .}] == 1 } {\n"
"			modFont fixed .\n"
"		}\n"
"	}\n"
".mbar.opti.menu.fonts add command -label \"HelveticaBold\" -command {\n"
"		if {[catch { modFont -adobe-helvetica-bold-r-normal--14-140-75-75-p-82-iso8859-1 .}] == 1 } {\n"
"			modFont fixed .\n"
"		}\n"
"	}\n"
".mbar.opti.menu.fonts add command -label \"Lucida\" -command {\n"
"		if {[catch { modFont -b&h-lucidatypewriter-bold-r-normal-sans-14-140-75-75-m-90-iso8859-1 .}] == 1 } {\n"
"			modFont fixed .\n"
"		}\n"
"	}\n"
".mbar.opti.menu.fonts add command -label \"Fixed2\" -command {\n"
"		if {[catch { modFont -misc-fixed-medium-r-normal--14-110-100-100-c-70-iso8859-1 .}] == 1 } {\n"
"			modFont fixed .\n"
"		}\n"
"	}\n"
"menu .mbar.opti.menu.color -tearoff 0\n"
".mbar.opti.menu.color add command -label \"Black & White\" -command {modCol b&w}\n"
".mbar.opti.menu.color add command -label \"Color\" -command {modCol col}\n"
"button .mbar.help -activebackground $but_act_back_col -activeforeground black -background $but_back_col -font $but_font -foreground $but_fore_col -relief raised -text Help -command {\n"
"			if { $jitter_install == 0 } {\n"
"				errorMessage \"Cannot execute jitter => no help file\"\n"
"				return\n"
"			}\n"
"			catch {exec jitter -f help_gui.ini -g}\n"
"			ini2Help help_gui.ini help_gui.txt\n"
"			roWin \"Help file\" help_gui.txt \n"
"			exec rm -f help_gui.txt\n"
"			exec rm -f help_gui.ini\n"
"		}\n"
"label .file_selected -background $lab_back_col -borderwidth 2 -font $but_font -foreground black -relief flat -textvariable currentfile\n"
"set topc [canvas .canv -yscrollcommand \".scrolly set\"]\n"
"scrollbar .scrolly -orient vertical -command \"$topc yview\"\n"
"pack .scrolly -fill y -side right\n"
"pack $topc -fill both -expand true -side bottom\n"
"pack .mbar -side top -fill x\n"
"pack .mbar.file -side left\n"
"pack .mbar.opti -side left\n"
"pack .mbar.help -side right\n"
"pack .file_selected -side top -fill x\n"
"if { $argc > 0 } {if { [lindex $argv 0] == \"-\" } {if { $argc > 1 } {set currentfile [lindex $argv 1]\n"
"pack .file_selected\n"
"file2Array\n"
"displayArray}} else {set currentfile [lindex $argv 0]\n"
"pack .file_selected\n"
"file2Array\n"
"displayArray}}}\n"
"proc Start {} {global jitter_install\n"
"global but_font\n"
"set lit_font 8x13\n"
"set but_font 8x13bold\n"
"set jitter_install 1\n"
"if [catch {set ecl_version [exec jitter --version]} resId] {errorMessage \"Cannot execute jitter --version\"\n"
"set jitter_install 0\n"
"set ecl_version \"?\"}\n"
"frame .f\n"
"label .f.l -text \"Welcome to GUI for the jitter\"\n"
"pack .f.l -in .f -side top\n"
"label .f.l2 -text \"This GUI supports eclipse version 4.5.0\" -font $lit_font\n"
"pack .f.l2 -in .f -side top\n"
"label .f.l3 -text \"Actual eclipse version: $ecl_version\" -font $lit_font\n"
"pack .f.l3 -in .f -side top\n"
"button .f.b -text \"Start GUI\" -command {\n"
"		destroy .f\n"
"		mainProg\n"
"    }\n"
"pack .f.b -in .f -side top -expand 1 -fill both\n"
"button .f.b2 -text \"Exit\" -command exit\n"
"pack .f.b2 -in .f -side top\n"
"pack .f}\n"
"Start\n"
"proc roWin {title file} {if { ![file exists $file] } {errorMessage \"Cannot find $file\"\n"
"return}\n"
"if { [winfo exists .rowindow] == 1 } {destroy .rowindow}\n"
"toplevel .rowindow\n"
"wm title .rowindow $title\n"
"frame .rowindow.t\n"
"text .rowindow.t.text -relief sunken -bd 2 -yscrollcommand \".rowindow.t.scr_help set\"\n"
"scrollbar .rowindow.t.scr_help -command \".rowindow.t.text yview\"\n"
"pack .rowindow.t.scr_help -side right -fill y\n"
"pack .rowindow.t.text -fill both -side left -expand true\n"
"pack .rowindow.t -fill both -side top -expand true\n"
"loadFile .rowindow.t.text $file\n"
"button .rowindow.b -text Dismiss -command { destroy .rowindow }\n"
"pack .rowindow.b -side bottom -anchor s}\n"
"proc loadFile {win file} {$win delete 1.0 end\n"
"set f [open $file]\n"
"while {![eof $f]} {$win insert end [read $f 1000]}\n"
"close $f}\n"
"proc modFont {font widget} {set child [winfo children $widget]\n"
"foreach x $child {if { ([winfo class $x] == \"Label\") } {$x config -font $font} elseif {[winfo class $x] == \"Entry\"} {$x config -font $font} elseif {[winfo class $x] == \"Button\"} {$x config -font $font} elseif {[winfo class $x] == \"Checkbutton\"} {$x config -font $font} elseif {[winfo class $x] == \"Radiobutton\"} {$x config -font $font} elseif {[winfo class $x] == \"Frame\"} {modFont $font $x} elseif {[winfo class $x] == \"Canvas\"} {modFont $font $x}}\n"
"return}\n"
"proc modCol { col_type } {global but_act_back_col\n"
"global but_back_col\n"
"global but_fore_col\n"
"global lab_back_col\n"
"if { $col_type == \"col\" } {set but_act_back_col cyan3\n"
"set but_back_col cyan2\n"
"set but_fore_col blue\n"
"set lab_back_col SkyBlue1} elseif {$col_type == \"b&w\"} {set but_act_back_col white\n"
"set but_back_col white\n"
"set but_fore_col black\n"
"set lab_back_col white}\n"
".mbar config -background $lab_back_col\n"
".mbar.file config -activebackground $but_act_back_col -background $but_back_col -foreground $but_fore_col\n"
".mbar.opti config -activebackground $but_act_back_col -background $but_back_col -foreground $but_fore_col\n"
".mbar.help config -activebackground $but_act_back_col -background $but_back_col -foreground $but_fore_col\n"
".file_selected config -background $lab_back_col\n"
"return}\n"
"proc greyOut {widget} {global children\n"
"set children [winfo children $widget]\n"
"foreach x $children {if { ([winfo class $x] == \"Label\") } {$x config -foreground grey50} elseif {[winfo class $x] == \"Entry\"} {$x config -state disabled\n"
"$x config -foreground grey50} elseif {[winfo class $x] == \"Button\"} {$x config -state disabled} elseif {[winfo class $x] == \"Checkbutton\"} {$x config -state disabled} elseif {[winfo class $x] == \"Radiobutton\"} {$x config -state disabled} elseif {[winfo class $x] == \"Frame\"} {greyOut $x} elseif {[winfo class $x] == \"Canvas\"} {} elseif {[winfo class $x] == \"Scrollbar\"} {}}\n"
"return}\n"
"proc greyIn {widget} {global topc\n"
"global children\n"
"global refine\n"
"global pp3_start\n"
"global input_offset\n"
"global source_type\n"
"set children [winfo children $widget]\n"
"foreach x $children {if { ([winfo class $x] == \"Label\") } {$x config -foreground black} elseif {[winfo class $x] == \"Entry\"} {$x config -state normal\n"
"$x config -foreground black} elseif {[winfo class $x] == \"Button\"} {$x config -state normal} elseif {[winfo class $x] == \"Checkbutton\"} {$x config -state normal} elseif {[winfo class $x] == \"Radiobutton\"} {$x config -state normal} elseif {[winfo class $x] == \"Frame\"} {greyIn $x} elseif {[winfo class $x] == \"Canvas\"} {} elseif {[winfo class $x] == \"Scrollbar\"} {}}\n"
"if { $refine == 0 } {greyOut $topc.saa.asaa.refine}\n"
"if { $pp3_start == 0 } {greyOut $topc.post.activ.start.command}\n"
"if { $input_offset != \"file\" } {greyOut $topc.saa.asaa.file}\n"
"if { $source_type != \"auto\" } {greyOut $topc.saa.asaa.peak}\n"
"if { $source_type != \"file\" } {greyOut $topc.saa.asaa.userobj}\n"
"return}\n"
"proc blockLabEnt { widget lab ent_size section keyword } {global keyarray\n"
"global found_pos\n"
"global found_val\n"
"global ent_sec\n"
"global ent_key\n"
"set ent_sec($widget.ent) $section\n"
"set ent_key($widget.ent) $keyword\n"
"frame $widget\n"
"label $widget.lab -text $lab\n"
"entry $widget.ent -width $ent_size\n"
"bind $widget.ent <Return> {\n"
"		findInArray $ent_sec(%W) $ent_key(%W)\n"
"        set keyarray($found_pos) [%W get]\n"
"    }\n"
"findInArray $section $keyword\n"
"$widget.ent insert 0 $found_val\n"
"pack $widget.lab -side left\n"
"pack $widget.ent -side right\n"
"return}\n"
"proc displayArray {} {global keyarray\n"
"global currentfile\n"
"global xpos\n"
"global ypos\n"
"global std_entry_size\n"
"global lit_entry_size\n"
"global indent\n"
"global topc\n"
"global jitter_install\n"
"set xpos 2\n"
"set ypos 2\n"
"set std_entry_size 20\n"
"set lit_entry_size 5\n"
"set indent [expr [winfo screenmmwidth .]/10]\n"
"set array_size [array size keyarray]\n"
"if {$array_size == 0} return\n"
"if { [info exists topc] } {destroy $topc\n"
"destroy .scrolly\n"
"set topc [canvas .canv -yscrollcommand \".scrolly set\"]\n"
"scrollbar .scrolly -orient vertical -command \"$topc yview\"\n"
"pack .scrolly -fill y -side right\n"
"pack $topc -fill both -expand true -side top}\n"
"set line_height 28\n"
"set line_width 600\n"
"if { [winfo exists .launch] } {destroy .launch}\n"
"displayGeneralSection $line_width $line_height\n"
"$topc create line 0 $ypos [winfo screenmmwidth .] $ypos -width 1\n"
"incr ypos\n"
"displayFramesSection $line_width $line_height\n"
"$topc create line 0 $ypos [winfo screenmmwidth .] $ypos -width 1\n"
"incr ypos\n"
"displayPreProcessingSection $line_width $line_height\n"
"$topc create line 0 $ypos [winfo screenmmwidth .] $ypos -width 1\n"
"incr ypos\n"
"displayCalibrationDataSection $line_width $line_height\n"
"$topc create line 0 $ypos [winfo screenmmwidth .] $ypos -width 1\n"
"incr ypos\n"
"displaySkySection $line_width $line_height\n"
"$topc create line 0 $ypos [winfo screenmmwidth .] $ypos -width 1\n"
"incr ypos\n"
"displayShiftAndAddSection $line_width $line_height\n"
"$topc create line 0 $ypos [winfo screenmmwidth .] $ypos -width 1\n"
"incr ypos\n"
"displayPostProcessingSection $line_width $line_height\n"
"$topc create line 0 $ypos [winfo screenmmwidth .] $ypos -width 1\n"
"incr ypos\n"
"displayOutputSection $line_width $line_height\n"
"$topc config -scrollregion \"0 0 [winfo reqwidth $topc.se] $ypos\" -width [winfo reqwidth $topc.se]\n"
"button .launch -text \"Save and launch jitter with this config\" -background grey70 -command {\n"
"			if { $jitter_install == 0 } { \n"
"				errorMessage \"Cannot execute jitter\"\n"
"				return\n"
"			}\n"
"			saveFile	\n"
"			wm iconify . \n"
"			toplevel .waitwin\n"
"			label .waitwin.t -text \"jitter is running - please wait ... \"\n"
"			pack .waitwin.t -side top\n"
"			tkwait visibility .waitwin.t\n"
"			catch {exec jitter -f $currentfile >&@ stdout}\n"
"			destroy .waitwin\n"
"			wm deiconify .\n"
"		}\n"
"pack .launch -side bottom -fill x\n"
"modFont fixed .\n"
"return}\n"
"proc displayGeneralSection { line_width line_height } {global topc\n"
"global keyarray\n"
"global currentfile\n"
"global xpos\n"
"global ypos\n"
"global found_val\n"
"global found_pos\n"
"global indent\n"
"global inst_type\n"
"frame $topc.g -height [expr 4*$line_height] -width $line_width\n"
"$topc create window $xpos $ypos -window $topc.g -anchor nw\n"
"incr ypos [winfo reqheight $topc.g]\n"
"label $topc.g.lab -text \"General -\"\n"
"pack $topc.g.lab -side top -anchor nw\n"
"findInArray General Eclipse\n"
"label $topc.g.lab2 -text \"Eclipse version: $found_val\"\n"
"pack $topc.g.lab2 -side top -anchor nw -padx $indent -fill x\n"
"frame $topc.g.inst\n"
"findInArray General Algorithm\n"
"set inst_type $found_val\n"
"radiobutton $topc.g.inst.auto_rbut -text \"auto\" -variable inst_type -value auto -command {\n"
"			findInArray General Algorithm\n"
"			set keyarray($found_pos) \"auto\"\n"
"		}\n"
"pack $topc.g.inst.auto_rbut -side left -anchor nw\n"
"radiobutton $topc.g.inst.isw_rbut -text \"isaac-sw\" -variable inst_type -value isaac-sw -command {\n"
"			findInArray General Algorithm \n"
"			set keyarray($found_pos) \"isaac-sw\"\n"
"		}\n"
"pack $topc.g.inst.isw_rbut -side left -anchor nw\n"
"radiobutton $topc.g.inst.ilw_rbut -text \"isaac-lw\" -variable inst_type -value isaac-lw -command {\n"
"			findInArray General Algorithm \n"
"			set keyarray($found_pos) \"isaac-lw\"\n"
"		}\n"
"pack $topc.g.inst.ilw_rbut -side left -anchor nw\n"
"radiobutton $topc.g.inst.nsw_rbut -text \"naco-sw\" -variable inst_type -value naco-sw -command {\n"
"			findInArray General Algorithm \n"
"			set keyarray($found_pos) \"naco-sw\"\n"
"		}\n"
"pack $topc.g.inst.nsw_rbut -side left -anchor nw\n"
"pack $topc.g.inst -side top -anchor nw -padx $indent -fill x\n"
"button $topc.g.but -text \"Update with the current instrument defaults\" -command {\n"
"			findInArray General Algorithm\n"
"			catch { exec jitter -g -A $found_val -f default_jitter.ini}\n"
"		    set currentfile \"default_jitter.ini\"\n"
"		    file2Array\n"
"		    pack .file_selected\n"
"		    displayArray\n"
"	}\n"
"pack $topc.g.but -side top\n"
"return}\n"
"proc displayFramesSection { line_width line_height } {global topc\n"
"global keyarray\n"
"global xpos\n"
"global ypos\n"
"global found_val\n"
"global found_pos\n"
"global indent\n"
"global std_entry_size\n"
"global lit_entry_size\n"
"global ent_sec\n"
"global ent_key\n"
"frame $topc.f -height [expr 5*$line_height] -width $line_width\n"
"$topc create window $xpos $ypos -window $topc.f -anchor nw\n"
"incr ypos [winfo reqheight $topc.f]\n"
"frame $topc.f.filelist\n"
"label $topc.f.filelist.lab1 -text \"Frames -\"\n"
"pack $topc.f.filelist.lab1 -side left\n"
"label $topc.f.filelist.lab2 -text \"FileList\"\n"
"pack $topc.f.filelist.lab2 -side left\n"
"entry $topc.f.filelist.ent -width $std_entry_size\n"
"bind $topc.f.filelist.ent <Return> {\n"
"		findInArray Frames FileList\n"
"		set keyarray($found_pos) [$topc.f.filelist.ent get]	\n"
"	}\n"
"findInArray Frames FileList\n"
"$topc.f.filelist.ent insert 0 $found_val\n"
"set ent_sec($topc.f.filelist.ent) \"Frames\"\n"
"set ent_key($topc.f.filelist.ent) \"FileList\"\n"
"pack $topc.f.filelist.ent -side left\n"
"button $topc.f.filelist.but -text View -command {\n"
"		roWin \"List of frames\" [$topc.f.filelist.ent get]\n"
"	}\n"
"pack $topc.f.filelist.but -side left\n"
"pack $topc.f.filelist -side top -anchor nw -fill x\n"
"blockLabEnt $topc.f.rejbot \"Bottom rejection\" $lit_entry_size Frames RejectBottom\n"
"blockLabEnt $topc.f.rejtop \"Top rejection\" $lit_entry_size Frames RejectTop\n"
"blockLabEnt $topc.f.rejlef \"Left rejection\" $lit_entry_size Frames RejectLeft\n"
"blockLabEnt $topc.f.rejrig \"Right rejection\" $lit_entry_size Frames RejectRight\n"
"pack $topc.f.rejbot -side top -anchor nw -padx $indent -fill x\n"
"pack $topc.f.rejtop -side top -anchor nw -padx $indent -fill x\n"
"pack $topc.f.rejlef -side top -anchor nw -padx $indent -fill x\n"
"pack $topc.f.rejrig -side top -anchor nw -padx $indent -fill x\n"
"return}\n"
"proc displayPreProcessingSection { line_width line_height } {global topc\n"
"global keyarray\n"
"global xpos\n"
"global ypos\n"
"global found_val\n"
"global found_pos\n"
"global indent\n"
"global prep_act\n"
"global prep_oe\n"
"global prep_hz\n"
"frame $topc.prep -height [expr 3*$line_height] -width $line_width\n"
"$topc create window $xpos $ypos -window $topc.prep -anchor nw\n"
"incr ypos [winfo reqheight $topc.prep]\n"
"findInArray PreProcessing Activate\n"
"if { $found_val == \"yes\" } {set prep_act 1} else {set prep_act 0}\n"
"checkbutton $topc.prep.cbut -text \"Activate pre-processing\" -variable prep_act -command {\n"
"			findInArray PreProcessing Activate \n"
"			if { $prep_act == 0 } {\n"
"				set keyarray($found_pos) \"no\"\n"
"				greyOut $topc.prep.activ\n"
"			} else {\n"
"				set keyarray($found_pos) \"yes\"\n"
"				greyIn $topc.prep.activ\n"
"			}\n"
"		}\n"
"pack $topc.prep.cbut -side top -anchor nw\n"
"frame $topc.prep.activ\n"
"findInArray PreProcessing OddEvenCorrection\n"
"if { $found_val == \"yes\" } {set prep_oe 1} else {set prep_oe 0}\n"
"checkbutton $topc.prep.activ.cbut -text \"Odd - Even correction\" -variable prep_oe -command {\n"
"			findInArray PreProcessing OddEvenCorrection \n"
"			if { $prep_oe == 0 } {\n"
"				set keyarray($found_pos) \"no\"\n"
"			} else {\n"
"				set keyarray($found_pos) \"yes\"\n"
"			}\n"
"		}\n"
"pack $topc.prep.activ.cbut -side top -anchor nw\n"
"findInArray PreProcessing FiftyHertzCorrection\n"
"if { $found_val == \"yes\" } {set prep_hz 1} else {set prep_hz 0}\n"
"checkbutton $topc.prep.activ.cbut2 -text \"Fifty Herz correction\" -variable prep_hz -command {\n"
"			findInArray PreProcessing FiftyHertzCorrection\n"
"			if { $prep_hz == 0 } {\n"
"				set keyarray($found_pos) \"no\"\n"
"			} else {\n"
"				set keyarray($found_pos) \"yes\"\n"
"			}\n"
"		}\n"
"pack $topc.prep.activ.cbut2 -side top -anchor nw\n"
"pack $topc.prep.activ -side top -anchor nw -padx $indent\n"
"if { $prep_act == 0 } {greyOut $topc.prep.activ}\n"
"return}\n"
"proc displayCalibrationDataSection { line_width line_height } {global topc\n"
"global xpos\n"
"global ypos\n"
"global found_val\n"
"global std_entry_size\n"
"global last_valid_dark\n"
"global last_valid_flat\n"
"global last_valid_badp\n"
"global d_subt\n"
"global bp_rep\n"
"global ff_div\n"
"frame $topc.dffbp -height [expr 3*$line_height] -width $line_width\n"
"$topc create window $xpos $ypos -window $topc.dffbp -anchor nw\n"
"incr ypos [winfo reqheight $topc.dffbp]\n"
"frame $topc.dffbp.d\n"
"set last_valid_dark \"none\"\n"
"findInArray CalibrationData Dark\n"
"if { $found_val == \"none\" } {set d_subt 0} else {set d_subt 1}\n"
"checkbutton $topc.dffbp.d.cbut -text \"Dark subtract -\" -variable d_subt -command { \n"
"			findInArray CalibrationData Dark\n"
"			if { $d_subt == 0 } {\n"
"				set last_valid_dark [$topc.dffbp.d.file.ent get]\n"
"				$topc.dffbp.d.file.ent delete 0 end\n"
"				$topc.dffbp.d.file.ent insert 0 \"none\"\n"
"				greyOut $topc.dffbp.d.file\n"
"			} else {\n"
"				greyIn $topc.dffbp.d.file\n"
"				$topc.dffbp.d.file.ent delete 0 end\n"
"				$topc.dffbp.d.file.ent insert 0 $last_valid_dark\n"
"			}\n"
"		}\n"
"blockLabEnt $topc.dffbp.d.file \"Filename\" $std_entry_size CalibrationData Dark\n"
"pack $topc.dffbp.d.cbut -side left\n"
"pack $topc.dffbp.d.file -side right\n"
"if { $d_subt == 0 } {greyOut $topc.dffbp.d.file}\n"
"pack $topc.dffbp.d -side top -anchor nw -fill x\n"
"frame $topc.dffbp.ff\n"
"set last_valid_flat \"none\"\n"
"findInArray CalibrationData FlatField\n"
"if { $found_val == \"none\" } {set ff_div 0} else {set ff_div 1}\n"
"checkbutton $topc.dffbp.ff.cbut -text \"Flat-field divide -\" -variable ff_div -command { \n"
"			findInArray CalibrationData FlatField\n"
"			if { $ff_div == 0 } {\n"
"				set last_valid_flat [$topc.dffbp.ff.file.ent get]\n"
"				$topc.dffbp.ff.file.ent delete 0 end\n"
"				$topc.dffbp.ff.file.ent insert 0 \"none\"\n"
"				greyOut $topc.dffbp.ff.file\n"
"			} else {\n"
"				greyIn $topc.dffbp.ff.file\n"
"				$topc.dffbp.ff.file.ent delete 0 end\n"
"				$topc.dffbp.ff.file.ent insert 0 $last_valid_flat\n"
"			}\n"
"		}\n"
"blockLabEnt $topc.dffbp.ff.file \"Filename\" $std_entry_size CalibrationData FlatField\n"
"pack $topc.dffbp.ff.cbut -side left\n"
"pack $topc.dffbp.ff.file -side right\n"
"if { $ff_div == 0 } {greyOut $topc.dffbp.ff.file}\n"
"pack $topc.dffbp.ff -side top -anchor nw -fill x\n"
"frame $topc.dffbp.bp\n"
"set last_valid_badp \"none\"\n"
"findInArray CalibrationData BadPixelMap\n"
"if { $found_val == \"none\" } {set bp_rep 0} else {set bp_rep 1}\n"
"checkbutton $topc.dffbp.bp.cbut -text \"Bad pixel replace -\" -variable bp_rep -command { \n"
"			findInArray CalibrationData BadPixelMap\n"
"			if { $bp_rep == 0 } {\n"
"				set last_valid_badp [$topc.dffbp.bp.file.ent get]\n"
"				$topc.dffbp.bp.file.ent delete 0 end\n"
"				$topc.dffbp.bp.file.ent insert 0 \"none\"\n"
"				greyOut $topc.dffbp.bp.file\n"
"			} else {\n"
"				greyIn $topc.dffbp.bp.file\n"
"				$topc.dffbp.bp.file.ent delete 0 end\n"
"				$topc.dffbp.bp.file.ent insert 0 $last_valid_badp\n"
"			}\n"
"		}\n"
"blockLabEnt $topc.dffbp.bp.file \"Filename\" $std_entry_size CalibrationData BadPixelMap\n"
"pack $topc.dffbp.bp.cbut -side left\n"
"pack $topc.dffbp.bp.file -side right\n"
"if { $bp_rep == 0 } {greyOut $topc.dffbp.bp.file}\n"
"pack $topc.dffbp.bp -side top -anchor nw -fill x\n"
"return}\n"
"proc displaySkySection { line_width line_height } {global topc\n"
"global keyarray\n"
"global xpos\n"
"global ypos\n"
"global found_val\n"
"global found_pos\n"
"global indent\n"
"global lit_entry_size\n"
"global sky_method\n"
"global se1_est\n"
"global se4_diff\n"
"frame $topc.se -height [expr 7*$line_height] -width $line_width\n"
"$topc create window $xpos $ypos -window $topc.se -anchor nw\n"
"incr ypos [winfo reqheight $topc.se]\n"
"findInArray SkyEngine EstimateSky\n"
"if { $found_val == \"yes\" } {set se1_est 1} else {set se1_est 0}\n"
"checkbutton $topc.se.cbut -text \"Activate sky engine\" -variable se1_est -command {\n"
"			findInArray SkyEngine EstimateSky\n"
"			if { $se1_est == 0 } {\n"
"				set keyarray($found_pos) \"no\"\n"
"				greyOut $topc.se.ase\n"
"			} else {\n"
"				set keyarray($found_pos) \"yes\"\n"
"				greyIn $topc.se.ase\n"
"			}\n"
"		}\n"
"pack $topc.se.cbut -side top -anchor nw\n"
"frame $topc.se.ase\n"
"findInArray SkyEngine OutputDiff\n"
"if { $found_val == \"yes\" } {set se4_diff 1} else {set se4_diff 0}\n"
"checkbutton $topc.se.ase.out_cbut -text \"Output difference frames\" -variable se4_diff -command {\n"
"			findInArray SkyEngine OutputDiff\n"
"			if { $se4_diff == 0 } {\n"
"				set keyarray($found_pos) \"no\"\n"
"			} else {\n"
"				set keyarray($found_pos) \"yes\"\n"
"			}\n"
"		}\n"
"pack $topc.se.ase.out_cbut -side top -anchor nw -padx $indent\n"
"frame $topc.se.ase.met\n"
"findInArray SkyEngine Method\n"
"set sky_method $found_val\n"
"radiobutton $topc.se.ase.met.auto_rbut -text \"auto\" -variable sky_method -value auto -command {\n"
"			findInArray SkyEngine Method \n"
"			set keyarray($found_pos) \"auto\"\n"
"		}\n"
"pack $topc.se.ase.met.auto_rbut -side left -anchor nw\n"
"radiobutton $topc.se.ase.met.com_rbut -text \"combine\" -variable sky_method -value combine -command {\n"
"			findInArray SkyEngine Method \n"
"			set keyarray($found_pos) \"combine\"\n"
"		}\n"
"pack $topc.se.ase.met.com_rbut -side left -anchor nw\n"
"radiobutton $topc.se.ase.met.commc_rbut -text \"combine_mc\" -variable sky_method -value combine_mc -command {\n"
"			findInArray SkyEngine Method \n"
"			set keyarray($found_pos) \"combine_mc\"\n"
"		}\n"
"pack $topc.se.ase.met.commc_rbut -side left -anchor nw\n"
"radiobutton $topc.se.ase.met.med_rbut -text \"median\" -variable sky_method -value median -command {\n"
"			findInArray SkyEngine Method \n"
"			set keyarray($found_pos) \"median\"\n"
"		}\n"
"pack $topc.se.ase.met.med_rbut -side left -anchor nw\n"
"pack $topc.se.ase.met -side top -anchor nw -padx $indent -fill x\n"
"label $topc.se.ase.lab -text \"Sky Combination\"\n"
"pack $topc.se.ase.lab -side top -anchor nw\n"
"blockLabEnt $topc.se.ase.mnf \"Minimum Number of frames\" $lit_entry_size SkyCombine MinNumberOfFrames\n"
"pack $topc.se.ase.mnf -side top -anchor nw -fill x -padx $indent -fill x\n"
"blockLabEnt $topc.se.ase.rej_hal \"Reject HalfWidth\" $lit_entry_size SkyCombine RejectHalfWidth\n"
"pack $topc.se.ase.rej_hal -side top -anchor nw -padx $indent -fill x\n"
"blockLabEnt $topc.se.ase.rej_min \"Reject Min\" $lit_entry_size SkyCombine RejectMin\n"
"pack $topc.se.ase.rej_min -side top -anchor nw -padx $indent -fill x\n"
"blockLabEnt $topc.se.ase.rej_max \"Reject Max\" $lit_entry_size SkyCombine RejectMax\n"
"pack $topc.se.ase.rej_max -side top -anchor nw -padx $indent -fill x\n"
"findInArray SkyCombine SeparateQuadrants\n"
"if { $found_val == \"yes\" } {set sky_quad 1} else {set sky_quad 0}\n"
"checkbutton $topc.se.ase.quad_cbut -text \"Separate quadrants\" -variable sky_quad -command {\n"
"			findInArray PreProcessing FiftyHertzCorrection\n"
"			if { $sky_quad == 0 } {\n"
"				set keyarray($found_pos) \"no\"\n"
"			} else {\n"
"				set keyarray($found_pos) \"yes\"\n"
"			}\n"
"		}\n"
"pack $topc.se.ase.quad_cbut -side top -anchor nw -padx $indent\n"
"pack $topc.se.ase -side top -anchor nw -padx $indent\n"
"if { $se1_est == 0 } {greyOut $topc.se.ase}\n"
"return}\n"
"proc displayShiftAndAddSection { line_width line_height } {global topc\n"
"global keyarray\n"
"global xpos\n"
"global ypos\n"
"global found_val\n"
"global found_pos\n"
"global indent\n"
"global lit_entry_size\n"
"global std_entry_size\n"
"global ent_sec\n"
"global ent_key\n"
"global saa_apply\n"
"global saa_union\n"
"global source_type\n"
"global input_offset\n"
"global detect_image\n"
"global out_obj\n"
"global refine\n"
"set keyw_ent_size 45\n"
"frame $topc.saa -height [expr 24*$line_height] -width $line_width\n"
"$topc create window $xpos $ypos -window $topc.saa -anchor nw\n"
"incr ypos [winfo reqheight $topc.saa]\n"
"findInArray ShiftAndAdd Activate\n"
"if { $found_val == \"yes\" } {set saa_apply 1} else {set saa_apply 0}\n"
"checkbutton $topc.saa.cbut -text \"Activate Shift and Add\" -variable saa_apply -command {\n"
"			findInArray ShiftAndAdd Activate \n"
"			if { $saa_apply == 0 } {\n"
"				set keyarray($found_pos) \"no\"\n"
"				greyOut $topc.saa.asaa \n"
"			} else {\n"
"				set keyarray($found_pos) \"yes\"\n"
"				greyIn $topc.saa.asaa\n"
"			}\n"
"		}\n"
"pack $topc.saa.cbut -side top -anchor nw\n"
"frame $topc.saa.asaa\n"
"findInArray ShiftAndAdd ObjectSource\n"
"set source_type $found_val\n"
"label $topc.saa.asaa.lab1 -text \"Cross-correlation object source:\"\n"
"pack $topc.saa.asaa.lab1 -side top -anchor nw\n"
"radiobutton $topc.saa.asaa.au_rbut -text \"auto\" -variable source_type -value auto -command {\n"
"			findInArray ShiftAndAdd ObjectSource \n"
"			set keyarray($found_pos) \"auto\"\n"
"			greyIn $topc.saa.asaa.peak\n"
"			greyOut $topc.saa.asaa.userobj\n"
"		}\n"
"pack $topc.saa.asaa.au_rbut -side top -anchor nw\n"
"frame $topc.saa.asaa.peak\n"
"label $topc.saa.asaa.peak.lab -text \"Peak detection settings\"\n"
"pack $topc.saa.asaa.peak.lab -side top -anchor nw\n"
"frame $topc.saa.asaa.peak.detim\n"
"findInArray ShiftAndAdd AutoDetectImage\n"
"set detect_image $found_val\n"
"label $topc.saa.asaa.peak.detim.lab -text \"Detect image\"\n"
"radiobutton $topc.saa.asaa.peak.detim.diff_rbut -text diff -variable detect_image -value diff -command {\n"
"			findInArray ShiftAndAdd AutoDetectImage \n"
"			set keyarray($found_pos) \"diff\"\n"
"		}\n"
"radiobutton $topc.saa.asaa.peak.detim.first_rbut -text first -variable detect_image -value first -command {	\n"
"			findInArray ShiftAndAdd AutoDetectImage\n"
"			set keyarray($found_pos) \"first\"\n"
"		}\n"
"pack $topc.saa.asaa.peak.detim.lab -side left\n"
"pack $topc.saa.asaa.peak.detim.diff_rbut -side left\n"
"pack $topc.saa.asaa.peak.detim.first_rbut -side left\n"
"pack $topc.saa.asaa.peak.detim -side top -anchor nw -padx $indent -fill x\n"
"blockLabEnt $topc.saa.asaa.peak.thres \"Threshold\" $lit_entry_size ShiftAndAdd AutoThreshold\n"
"pack $topc.saa.asaa.peak.thres -side top -anchor nw -padx $indent -fill x\n"
"blockLabEnt $topc.saa.asaa.peak.mindet \"MinDetectPoints\" $lit_entry_size ShiftAndAdd AutoMinPoints\n"
"pack $topc.saa.asaa.peak.mindet -side top -anchor nw -padx $indent -fill x\n"
"blockLabEnt $topc.saa.asaa.peak.maxdet \"MaxDetectPoints\" $lit_entry_size ShiftAndAdd AutoMaxPoints\n"
"pack $topc.saa.asaa.peak.maxdet -side top -anchor nw -padx $indent -fill x\n"
"frame $topc.saa.asaa.peak.outobj\n"
"findInArray ShiftAndAdd AutoOutputObjects\n"
"if { $found_val == \"yes\" } {set out_obj 1} else {set out_obj 0}\n"
"checkbutton $topc.saa.asaa.peak.outobj.cbut -text \"Output objects\" -variable out_obj -command {\n"
"			findInArray ShiftAndAdd AutoOutputObjects \n"
"				if { $out_obj == 0 } {\n"
"					set keyarray($found_pos) \"no\"\n"
"				} else {\n"
"					set keyarray($found_pos) \"yes\"\n"
"				}\n"
"		}\n"
"pack $topc.saa.asaa.peak.outobj.cbut -side left\n"
"pack $topc.saa.asaa.peak.outobj -side top -anchor nw -padx $indent -fill x\n"
"if { $source_type != \"auto\" } {greyOut $topc.saa.asaa.peak}\n"
"pack $topc.saa.asaa.peak -side top -anchor nw -padx $indent\n"
"radiobutton $topc.saa.asaa.fi_rbut -text \"file\" -variable source_type -value file -command {\n"
"			findInArray ShiftAndAdd ObjectSource \n"
"			set keyarray($found_pos) \"file\"\n"
"			greyIn $topc.saa.asaa.userobj\n"
"			greyOut $topc.saa.asaa.peak\n"
"		}\n"
"pack $topc.saa.asaa.fi_rbut -side top -anchor nw\n"
"frame $topc.saa.asaa.userobj\n"
"label $topc.saa.asaa.userobj.lab -text \"User objects File Name\"\n"
"entry $topc.saa.asaa.userobj.ent -width $std_entry_size\n"
"bind $topc.saa.asaa.userobj.ent <Return> {\n"
"        findInArray ShiftAndAdd ObjectFileName \n"
"        set keyarray($found_pos) [$topc.saa.asaa.userobj.ent get]\n"
"    }\n"
"findInArray ShiftAndAdd ObjectFileName\n"
"$topc.saa.asaa.userobj.ent insert 0 $found_val\n"
"set ent_sec($topc.saa.asaa.userobj.ent) \"ShiftAndAdd\"\n"
"set ent_key($topc.saa.asaa.userobj.ent) \"ObjectFileName\"\n"
"button $topc.saa.asaa.userobj.but -text View -command {\n"
"        roWin \"Input object file\" [$topc.saa.asaa.userobj.ent get]\n"
"    }\n"
"pack $topc.saa.asaa.userobj.lab -side left\n"
"pack $topc.saa.asaa.userobj.ent -side left\n"
"pack $topc.saa.asaa.userobj.but -side left\n"
"if { $source_type != \"file\" } {greyOut $topc.saa.asaa.userobj}\n"
"pack $topc.saa.asaa.userobj -side top -anchor nw -padx $indent -fill x\n"
"findInArray ShiftAndAdd OffsetInput\n"
"set input_offset $found_val\n"
"label $topc.saa.asaa.emptylab1 -text \"\"\n"
"pack $topc.saa.asaa.emptylab1 -side top\n"
"label $topc.saa.asaa.lab2 -text \"Cross-correlation offset source:\"\n"
"pack $topc.saa.asaa.lab2 -side top -anchor nw\n"
"radiobutton $topc.saa.asaa.head_rbut -text \"Header\" -variable input_offset -value header -command {\n"
"			findInArray ShiftAndAdd OffsetInput\n"
"			set keyarray($found_pos) \"header\"\n"
"			greyOut $topc.saa.asaa.file\n"
"		}\n"
"pack $topc.saa.asaa.head_rbut -side top -anchor nw\n"
"radiobutton $topc.saa.asaa.file_rbut -text \"File\" -variable input_offset -value file -command {\n"
"			findInArray ShiftAndAdd OffsetInput \n"
"			set keyarray($found_pos) \"file\"\n"
"			greyIn $topc.saa.asaa.file\n"
"		}\n"
"pack $topc.saa.asaa.file_rbut -side top -anchor nw\n"
"frame $topc.saa.asaa.file\n"
"frame $topc.saa.asaa.file.input\n"
"label $topc.saa.asaa.file.input.lab -text \"Input File Name\"\n"
"entry $topc.saa.asaa.file.input.ent -width $std_entry_size\n"
"bind $topc.saa.asaa.file.input.ent <Return> {\n"
"		findInArray ShiftAndAdd OffsetInputFile\n"
"		set keyarray($found_pos) [$topc.saa.asaa.file.input.ent get]\n"
"	}\n"
"findInArray ShiftAndAdd OffsetInputFile\n"
"$topc.saa.asaa.file.input.ent insert 0 $found_val\n"
"set ent_sec($topc.saa.asaa.file.input.ent) \"ShiftAndAdd\"\n"
"set ent_key($topc.saa.asaa.file.input.ent) \"OffsetInputFile\"\n"
"button $topc.saa.asaa.file.input.but -text View -command {\n"
"		roWin \"List of frames\" [$topc.saa.asaa.file.input.ent get]\n"
"	}\n"
"pack $topc.saa.asaa.file.input.lab -side left\n"
"pack $topc.saa.asaa.file.input.ent -side left\n"
"pack $topc.saa.asaa.file.input.but -side left\n"
"pack $topc.saa.asaa.file.input -side top -anchor nw -fill x\n"
"pack $topc.saa.asaa.file -side top -anchor nw -padx $indent\n"
"if { $input_offset != \"file\" } {greyOut $topc.saa.asaa.file}\n"
"radiobutton $topc.saa.asaa.blind_rbut -text \"Blind\" -variable input_offset -value blind -command {\n"
"			findInArray ShiftAndAdd OffsetInput\n"
"			set keyarray($found_pos) \"blind\"\n"
"			greyOut $topc.saa.asaa.file\n"
"		}\n"
"pack $topc.saa.asaa.blind_rbut -side top -anchor nw\n"
"label $topc.saa.asaa.emptylab2 -text \"\"\n"
"pack $topc.saa.asaa.emptylab2 -side top\n"
"findInArray ShiftAndAdd OffsetRefine\n"
"if { $found_val == \"yes\" } {set refine 1} else {set refine 0}\n"
"checkbutton $topc.saa.asaa.cbut -text \"Refine inputs\" -variable refine -command {\n"
"			findInArray ShiftAndAdd OffsetRefine\n"
"			if { $refine == 0 } {\n"
"				set keyarray($found_pos) \"no\"\n"
"				greyOut $topc.saa.asaa.refine\n"
"			} else {\n"
"				set keyarray($found_pos) \"yes\"\n"
"				greyIn $topc.saa.asaa.refine\n"
"			}\n"
"		}\n"
"pack $topc.saa.asaa.cbut -side top -anchor nw\n"
"frame $topc.saa.asaa.refine\n"
"label $topc.saa.asaa.refine.lab1 -text \"Search box half size\"\n"
"pack $topc.saa.asaa.refine.lab1 -side top -anchor nw\n"
"blockLabEnt $topc.saa.asaa.refine.width1 \"Width\" $lit_entry_size ShiftAndAdd OffsetSearchSizeX\n"
"pack $topc.saa.asaa.refine.width1 -side top -anchor nw -padx $indent -fill x\n"
"blockLabEnt $topc.saa.asaa.refine.height1 \"Height\" $lit_entry_size ShiftAndAdd OffsetSearchSizeY\n"
"pack $topc.saa.asaa.refine.height1 -side top -anchor nw -padx $indent -fill x\n"
"label $topc.saa.asaa.refine.lab2 -text \"Measure box half size\"\n"
"pack $topc.saa.asaa.refine.lab2 -side top -anchor nw\n"
"blockLabEnt $topc.saa.asaa.refine.width2 \"Width\" $lit_entry_size ShiftAndAdd OffsetMeasureSizeX\n"
"pack $topc.saa.asaa.refine.width2 -side top -anchor nw -padx $indent -fill x\n"
"blockLabEnt $topc.saa.asaa.refine.height2 \"Height\" $lit_entry_size ShiftAndAdd OffsetMeasureSizeY\n"
"pack $topc.saa.asaa.refine.height2 -side top -anchor nw -padx $indent -fill x\n"
"pack $topc.saa.asaa.refine -side top -anchor nw -padx $indent\n"
"if { $refine == 0 } {greyOut $topc.saa.asaa.refine}\n"
"label $topc.saa.asaa.emptylab3 -text \"\"\n"
"pack $topc.saa.asaa.emptylab3 -side top\n"
"frame $topc.saa.asaa.frameav\n"
"label $topc.saa.asaa.frameav.lab -text \"Frame average\"\n"
"pack $topc.saa.asaa.frameav.lab -side top -anchor nw\n"
"blockLabEnt $topc.saa.asaa.frameav.min \"Min Reject\" $lit_entry_size ShiftAndAdd AverageRejectMin\n"
"pack $topc.saa.asaa.frameav.min -side top -anchor nw -fill x\n"
"blockLabEnt $topc.saa.asaa.frameav.max \"Max Rejact\" $lit_entry_size ShiftAndAdd AverageRejectMax\n"
"pack $topc.saa.asaa.frameav.max -side top -anchor nw -fill x\n"
"findInArray ShiftAndAdd UnionFrame\n"
"if { $found_val == \"yes\" } {set saa_union 1} else {set saa_union 0}\n"
"checkbutton $topc.saa.asaa.frameav.union_cbut -text \"Union frame\" -variable saa_union -command {\n"
"			findInArray ShiftAndAdd UnionFrame \n"
"			if { $saa_union == 0 } {\n"
"				set keyarray($found_pos) \"no\"\n"
"			} else {\n"
"				set keyarray($found_pos) \"yes\"\n"
"			}\n"
"		}\n"
"pack $topc.saa.asaa.frameav.union_cbut -side top -anchor nw\n"
"pack $topc.saa.asaa.frameav -side top -anchor nw\n"
"pack $topc.saa.asaa -side top -anchor nw -padx $indent\n"
"if { $saa_apply == 0 } {greyOut $topc.saa.asaa}\n"
"return}\n"
"proc displayPostProcessingSection { line_width line_height } {global topc\n"
"global keyarray\n"
"global xpos\n"
"global ypos\n"
"global found_val\n"
"global found_pos\n"
"global indent\n"
"global std_entry_size\n"
"global pp1_post\n"
"global pp2_subt\n"
"global pp3_start\n"
"frame $topc.post -height [expr 3*$line_height] -width $line_width\n"
"$topc create window $xpos $ypos -window $topc.post -anchor nw\n"
"incr ypos [winfo reqheight $topc.post]\n"
"findInArray PostProcessing Activate\n"
"if { $found_val == \"yes\" } {set pp1_post 1} else {set pp1_post 0}\n"
"checkbutton $topc.post.cbut -text \"Activate post-processing\" -variable pp1_post -command {\n"
"			findInArray PostProcessing Activate \n"
"			if { $pp1_post == 0 } {\n"
"				set keyarray($found_pos) \"no\"\n"
"				greyOut $topc.post.activ\n"
"			} else {\n"
"				set keyarray($found_pos) \"yes\"\n"
"				greyIn $topc.post.activ\n"
"			}\n"
"		}\n"
"pack $topc.post.cbut -side top -anchor nw\n"
"frame $topc.post.activ\n"
"findInArray PostProcessing RowSubtractMedian\n"
"if { $found_val == \"yes\" } {set pp2_subt 1} else {set pp2_subt 0}\n"
"checkbutton $topc.post.activ.cbut -text \"Subtract row medians\" -variable pp2_subt -command {\n"
"			findInArray PostProcessing RowSubtractMedian\n"
"			if { $pp2_subt == 0 } {\n"
"				set keyarray($found_pos) \"no\"\n"
"			} else {\n"
"				set keyarray($found_pos) \"yes\"\n"
"			}\n"
"		}\n"
"pack $topc.post.activ.cbut -side top -anchor nw\n"
"frame $topc.post.activ.start\n"
"findInArray PostProcessing StartViewer\n"
"if { $found_val == \"yes\" } {set pp3_start 1} else {set pp3_start 0}\n"
"checkbutton $topc.post.activ.start.cbut -text \"Start viewer -\" -variable pp3_start -command {\n"
"			findInArray PostProcessing StartViewer\n"
"			if { $pp3_start == 0 } {\n"
"				set keyarray($found_pos) \"no\"\n"
"				greyOut $topc.post.activ.start.command\n"
"			} else {\n"
"				set keyarray($found_pos) \"yes\"\n"
"				greyIn $topc.post.activ.start.command\n"
"			}\n"
"		}\n"
"blockLabEnt $topc.post.activ.start.command \"command\" $std_entry_size PostProcessing StartCommand\n"
"pack $topc.post.activ.start.cbut -side left\n"
"pack $topc.post.activ.start.command -side top -anchor nw\n"
"if { $pp3_start == 0 } {greyOut $topc.post.activ.start.command}\n"
"pack $topc.post.activ.start -side top -anchor nw\n"
"pack $topc.post.activ -side top -anchor nw -padx $indent\n"
"if { $pp1_post == 0 } {greyOut $topc.post.activ}\n"
"return}\n"
"proc displayOutputSection { line_width line_height } {global topc\n"
"global xpos\n"
"global ypos\n"
"global std_entry_size\n"
"frame $topc.out -height $line_height -width $line_width\n"
"$topc create window $xpos $ypos -window $topc.out -anchor nw\n"
"incr ypos [winfo reqheight $topc.out]\n"
"blockLabEnt $topc.out.out \"Output file base name\" $std_entry_size Output BaseName\n"
"pack $topc.out.out -side top -anchor nw -fill x\n"
"return}\n"
"proc saveFile {} {global keyarray\n"
"global currentfile\n"
"if { [array size keyarray] == 0 } {errorMessage \"No data to save\"\n"
"return}\n"
"if { $currentfile == \"No name\" } {errorMessage \"No file name specified\"\n"
"return}\n"
"updateEntries .\n"
"if [catch {open $currentfile w} fileId] {errorMessage \"Cannot open file $currentfile\"} else {set i 0\n"
"set j 1\n"
"set k 2\n"
"set array_size [array size keyarray]\n"
"set section $keyarray($i)\n"
"puts $fileId \"\\[$section\\]\"\n"
"puts $fileId \"$keyarray($j) = $keyarray($k)\"\n"
"while {$k<[expr $array_size-3]} {incr i 3\n"
"incr j 3\n"
"incr k 3\n"
"if {$section == $keyarray($i)} {puts $fileId \"$keyarray($j) = $keyarray($k)\"} else {set section $keyarray($i)\n"
"puts $fileId \"\\[$section\\]\"\n"
"puts $fileId \"$keyarray($j) = $keyarray($k)\"}}\n"
"close $fileId}\n"
"return}\n"
"proc openFile {} {global currentfile\n"
"global fileselect\n"
"global keyarray\n"
"catch { fileSelect }\n"
"if {$fileselect(path)==\"\"} return\n"
"set currentfile $fileselect(path)\n"
"pack .file_selected\n"
"file2Array\n"
"displayArray\n"
"return}\n"
"proc newFile {} {global keyarray\n"
"global currentfile\n"
"global jitter_install\n"
"if { $jitter_install == 0 } {errorMessage \"Cannot execute jitter -g\"\n"
"return}\n"
"catch { exec jitter -g }\n"
"set currentfile \"jitter.ini\"\n"
"file2Array\n"
"pack .file_selected\n"
"displayArray\n"
"return}\n"
"proc saveAsFile {} {global currentfile\n"
"global keyarray\n"
"global fileselect\n"
"global cont\n"
"catch { fileSelect \"File entry\" {} 0 }\n"
"if {$fileselect(path)==\"\"} return\n"
"if {[file exists $fileselect(path)]} {set cnf [toplevel .confirm]\n"
"wm title $cnf \"Confirmation\"\n"
"frame $cnf.que -width 500 -background white -borderwidth 5 -cursor hand2 -relief ridge\n"
"message $cnf.que.msg -width 500 -background black -borderwidth 5 -cursor hand2 -font 9x15bold -foreground white -justify center -relief ridge -text \"Do you want to overwrite the file $fileselect(path)?\"\n"
"button $cnf.que.ok -activebackground red -activeforeground black -background blue -borderwidth 5 -command \"set cont 1\" -font 8x13bold -foreground cyan -relief groove -text Yes\n"
"button $cnf.que.no -activebackground red -activeforeground black -background blue -borderwidth 5 -command \"set cont 0\" -font 8x13bold -foreground cyan -relief groove -text No\n"
"pack $cnf.que -side top -fill x\n"
"pack $cnf.que.msg\n"
"pack $cnf.que.ok -side left\n"
"pack $cnf.que.no -side right\n"
"tkwait variable cont\n"
"if {$cont} {destroy $cnf} else {destroy $cnf\n"
"return}}\n"
"if { [array size keyarray] == 0 } {errorMessage \"No data to save\"\n"
"return}\n"
"set currentfile $fileselect(path)\n"
"pack .file_selected\n"
"saveFile\n"
"return}\n"
"proc fileselectResources {} {option add *Fileselect*path.relief sunken startup\n"
"option add *Fileselect*path.background white startup\n"
"option add *Fileselect*path.foreground black startup\n"
"option add *Fileselect*l.text File: startup\n"
"option add *Fileselect*ok*text OK startup\n"
"option add *Fileselect*ok*underline 0 startup\n"
"option add *Fileselect*cancel.text Cancel startup\n"
"option add *Fileselect*cancel.underline 0 startup\n"
"option add *Fileselect*list.width 20 startup\n"
"option add *Fileselect*list.height 10 startup}\n"
"proc fileSelect {{why \"File Selection\"} {default {}} {mustExist 1} } {global fileselect\n"
"set t [toplevel .fileselect -bd 4 -class Fileselect]\n"
"fileselectResources\n"
"message $t.msg -aspect 1000 -text $why\n"
"pack $t.msg -side top -fill x\n"
"set fileselect(dirEnt) [entry $t.dir -width 15 -relief flat -state disabled]\n"
"pack $t.dir -side top -fill x\n"
"frame $t.top\n"
"label $t.top.l -padx 0\n"
"set e [entry $t.top.path -textvariable fileselect(path)]\n"
"pack $t.top -side top -fill x\n"
"pack $t.top.l -side left\n"
"pack $t.top.path -side right -fill x -expand true\n"
"set lb [listbox $t.list -yscrollcommand [list $t.scroll set]]\n"
"scrollbar $t.scroll -command [list $lb yview]\n"
"frame $t.buttons -bd 10\n"
"frame $t.buttons.ok -bd 2 -relief sunken\n"
"set ok [button $t.buttons.ok.b -command fileselectOK]\n"
"set can [button $t.buttons.cancel -command fileselectCancel]\n"
"pack $t.list -side left -fill both -expand true\n"
"pack $t.scroll -side left -fill y\n"
"pack $t.buttons -side left -fill both\n"
"pack $t.buttons.ok $t.buttons.cancel -side top -padx 10 -pady 5\n"
"pack $t.buttons.ok.b -padx 4 -pady 4\n"
"fileselectBindings $t $e $lb $ok $can\n"
"if {[string length $default] == 0} {set fileselect(path) {}\n"
"set dir [pwd]} else {set fileselect(path) [file tail $default]\n"
"set dir [file dirname $default]}\n"
"set fileselect(dir) {}\n"
"set fileselect(done) 0\n"
"set fileselect(mustExist) $mustExist\n"
"tkwait visibility .fileselect.list\n"
"fileselectList $dir\n"
"tkwait variable fileselect(done)\n"
"destroy $t\n"
"return $fileselect(path)}\n"
"proc fileselectBindings { t e lb ok can } {foreach w [list $e $lb $ok $can] {bindtags $w [list $t [winfo class $w] $w]}\n"
"bind $t <Control-c> fileselectCancel\n"
"bind $e <Return> fileselectOK\n"
"bind $e <space> fileselectComplete\n"
"bind $lb <space> \"fileselectTake $%W ; focus $e\"\n"
"bind $lb <Button-1> \"fileselectClick %W %y ; focus $e\"\n"
"bind $lb <Return> \"fileselectTake %W ; fileselectOK\"\n"
"bind $lb <Double-Button-1> \"fileselectClick %W %y ; fileselectOK\"\n"
"bind $e <Tab> \"focus $lb ; $lb select set 0\"\n"
"bind $lb <Tab> \"focus $e\"\n"
"foreach but [list $ok $can] {set char [string tolower [string index [$but cget -text] [$but cget -underline]]]\n"
"bind $t <Alt-$char> \"focus $but ; break\"}\n"
"bind $ok <Tab> \"focus $can\"\n"
"bind $can <Tab> \"focus $ok\"\n"
"focus $e}\n"
"proc fileselectList { dir {files {}} } {global fileselect\n"
"set e $fileselect(dirEnt)\n"
"$e config -state normal\n"
"$e delete 0 end\n"
"$e insert 0 $dir\n"
"$e config -state disabled\n"
"$e xview moveto 1\n"
".fileselect.list delete 0 end\n"
"set fileselect(dir) $dir\n"
"if ![file isdirectory $dir] {.fileselect.list insert 0 \"Bad Directory\"\n"
"return}\n"
".fileselect.list insert 0 Listing...\n"
"update idletasks\n"
".fileselect.list delete 0\n"
"if {[string length $files] == 0} {set err [catch {set files [glob -nocomplain $fileselect(dir)/*]}]\n"
".fileselect.list insert end ../}\n"
"set dirs {}\n"
"set others {}\n"
"foreach f [lsort $files] {if [file isdirectory $f] {lappend dirs [file tail $f]/} else {lappend others [file tail $f]}}\n"
"foreach f [concat $dirs $others] {.fileselect.list insert end $f}}\n"
"proc fileselectOK {} {global fileselect\n"
"if {[regsub {^\\.\\./?} $fileselect(path) {} newpath] != 0} {set fileselect(path) $newpath\n"
"set fileselect(dir) [file dirname $fileselect(dir)]\n"
"fileselectOK\n"
"return}\n"
"set path [string trimright $fileselect(dir)/$fileselect(path) /]\n"
"if [file isdirectory $path] {set fileselect(path) {}\n"
"fileselectList $path\n"
"return}\n"
"if [file exists $path] {set fileselect(path) $path\n"
"set fileselect(done) 1\n"
"return}\n"
"if [catch {glob $path} files] {if [catch {glob $fileselect(path)} path] {if {$fileselect(mustExist)} {fileselectComplete} elseif [file isdirectory [file dirname $fileselect(path)]] {set fileselect(done) 1}\n"
"return} else {set fileselect(dir) [file dirname $fileselect(path)]\n"
"set fileselect(path) [file tail $fileselect(path)]\n"
"fileselectOK\n"
"return}} else {if {[llength [split $files]] == 1} {set fileselect(path) $files\n"
"fileselectOK} else {set fileselect(dir) [file dirname [lindex $files 0]]\n"
"fileselectList $fileselect(dir) $files}}}\n"
"proc fileselectCancel {} {global fileselect\n"
"set fileselect(done) 1\n"
"set fileselect(path) {}}\n"
"proc fileselectClick { lb y } {global fileselect\n"
"set fileselect(path) [$lb get [$lb nearest $y]]}\n"
"proc fileselectTake { lb } {global fileselect\n"
"set fileselect(path) [$lb get [$lb curselection]]}\n"
"proc fileselectComplete {} {global fileselect\n"
"set fileselect(path) [string trim $fileselect(path) \\t\\ ]\n"
"if {[string match /* $fileselect(path)]} {set dir [file dirname $fileselect(path)]\n"
"set tail [file tail $fileselect(path)]} elseif [string match ~* $fileselect(path)] {if [catch {file dirname $fileselect(path)} dir] {return}\n"
"set tail [file tail $fileselect(path)]} else {set path $fileselect(dir)/$fileselect(path)\n"
"set dir [file dirname $path]\n"
"set tail [file tail $path]}\n"
"set files [glob -nocomplain $dir/$tail*]\n"
"if {[llength [split $files]] == 1} {set fileselect(dir) $dir\n"
"set fileselect(path) [file tail $files]} else {if {[llength [split $files]] > 1} {set l [expr [string length $tail]-1]\n"
"set miss 0\n"
"set file1 [file tail [lindex $files 0]]\n"
"while {!$miss} {incr l\n"
"if {$l == [string length $file1]} {break}\n"
"set new [string range $file1 0 $l]\n"
"foreach f $files {if ![string match $new* [file tail $f]] {set miss 1\n"
"incr l -1\n"
"break}}}\n"
"set fileselect(path) [string range $file1 0 $l]}\n"
"fileselectList $dir $files}}\n"
"proc file2Array {} {global keyarray\n"
"global currentfile\n"
"set i 0\n"
"if {[array exists keyarray]} {unset keyarray}\n"
"if [catch {open $currentfile r} fileId] {errorMessage \"Cannot open file $currentfile\"} else {set section \"Unknown section\"\n"
"while {![eof $fileId]} {gets $fileId curr_line\n"
"if {[regsub {^\\[[A-Z][a-zA-Z]*\\]} $curr_line {&} section_line]} {regsub {\\[} $section_line {} section\n"
"regsub {\\]} $section {} section}\n"
"if {[regsub {^[A-Z][A-Za-z]*} $curr_line {&} keyword_line]} {if {![regsub {=.*} $keyword_line {} keyword]} {errorMessage \"Sign = missing after a keyword in INI file.\"} else {regsub {( )*$} $keyword {} keyword\n"
"regsub {;.*} $keyword_line {} value_line\n"
"regsub {.*= } $value_line {} value\n"
"regsub {( )*$} $value {} value\n"
"set keyarray($i) $section\n"
"incr i\n"
"set keyarray($i) $keyword\n"
"incr i\n"
"set keyarray($i) $value\n"
"incr i}}}\n"
"close $fileId\n"
"if {[array size keyarray] == 0} {errorMessage \"No INI data in the file $currentfile\"}}\n"
"return}\n"
"proc ini2Help { inifile helpfile } {if [catch {open $inifile r} fileId] {errorMessage \"Cannot open file $inifile\"} else {if [catch {open $helpfile w} fileId2] {errorMessage \"Cannot open file $helpfile\"} else {while {![eof $fileId]} {gets $fileId curr_line\n"
"if {[regsub {^\\#} $curr_line {} help_line]} {puts $fileId2 $help_line}}}\n"
"close $fileId\n"
"close $fileId2}\n"
"return}\n"
"proc findInArray { section keyword } {global keyarray\n"
"global found_val\n"
"global found_pos\n"
"set found_val 0\n"
"set found_pos 0\n"
"set array_size [array size keyarray]\n"
"set i 0\n"
"set j 1\n"
"set k 2\n"
"while {$k<$array_size} {if {($keyarray($i) == $section) && ($keyarray($j) == $keyword)} {set found_pos $k\n"
"set found_val $keyarray($k)\n"
"return}\n"
"incr i 3\n"
"incr j 3\n"
"incr k 3}\n"
"if {$section != \"General\"} {errorMessage \"Value of \\[$section\\], $keyword not found in the array\"}\n"
"set found_pos -1\n"
"set found_val -1\n"
"return}\n"
"proc updateEntries { widget } {global keyarray\n"
"global found_pos\n"
"global ent_sec\n"
"global ent_key\n"
"global topc\n"
"set children [winfo children $widget]\n"
"foreach x $children {if { ([winfo class $x] == \"Entry\") } {findInArray $ent_sec($x) $ent_key($x)\n"
"set keyarray($found_pos) [$x get]} else {updateEntries $x}}\n"
"return}\n"
"\n";

/*----------------------------------------------------------------------------
                                Functions
 ---------------------------------------------------------------------------*/
int jitter_gui()
{
    FILE    *   wish ;

    if ((wish=popen("wish", "w"))==NULL) {
        printf("cannot run wish?\n");
        return -1 ;
    }
    fprintf(wish, "%s\n", tcl_code);
    fflush(wish);
    pclose(wish);
    return 0 ;
}


