
const char isaac_twflat_version[] = "$Revision: 1.6 $";
const char isaac_twflat_date[]="$Date: 2003/01/31 13:39:32 $";
int  isaac_twflat_main(void * d);

cmdline_spec isaac_twflat_cmd[] = {
	{'o', "output", "Output file(s) base name", 1, "filename"},
    {'i', "intercepts", "Outputs y-intercept image", 0, NULL},
    {'e', "errmap", "Output error map image", 0, NULL},
    {'b', "pixmap", "Output bad pixel map", 0, NULL},
    {'p', "prop", "Proportional fit only", 0, NULL},
    {'d', "dark", "Activate dark subtraction", 1, "filename"},
    {'t', "threshold", "Change thresholds for bad pixel map", 1, "'lo hi'"},
    {0, 0, 0, 0, 0}
};

const char isaac_twflat_man[] =
"NAME\n"
"       twflat -- ISAAC imaging twilight flat-field\n"
"\n"
"SYNOPSIS\n"
"       isaacp twflat [options] in\n"
"\n"
"DESCRIPTION\n"
"       flat is used to process twilight data cubes to create lin­\n"
"       ear gain maps and bad pixel maps. Twilight data cubes  are\n"
"       a  slowly increasing/decreasing signal that may be used to\n"
"       record pixels' responses. In this way, it is mainly possi­\n"
"       ble  to  see which pixels have a linear response, in which\n"
"       domain, and if the response is linear, a simple regression\n"
"       gives  the  pixel  gain,  relative to the mean (or median)\n"
"       gain.\n"
"\n"
"ALGORITHM\n"
"       twflat makes a computation of linear regression factors on\n"
"       every pixel, outputting the value of the fitted slope. The\n"
"       overall luminosity in each image is  approximated  by  the\n"
"       median  flux. This assumes a majority of pixels are valid,\n"
"       a valid assumption for standard detectors.\n"
"\n"
"       A rejection is applied on the time line  to  avoid  taking\n"
"       into  accounts  stellar objects which are seen in twilight\n"
"       frames. This is done by applying a robust linear fit.\n"
"       Byproducts of this computation are the y-intercept map, an\n"
"       error  map,  a bad pixel map. So far, the only used crite­\n"
"       rion to declare a pixel as bad is to tag all  pixels  out­\n"
"       side a [0.5, 2.0] gain interval as invalid. Some more cri­\n"
"       teria could be derived from a close  study  of  the  slope\n"
"       fit.\n"
"\n"
"       Output  file names are all named according to a base name.\n"
"       The gain map is called base_flat.fits, the  intercept  map\n"
"       is base_intercept.fits, the error map is base_errmap.fits,\n"
"       the bad pixel map is base_badpix.fits.  The base  name  is\n"
"       either  given  on  the  command-line  after the input file\n"
"       name, or it can be omitted on the  command-line.  In  that\n"
"       case,  the  input  file  base  name (i.e. without .FITS or\n"
"       .fits extension) will be used.\n"
"\n"
"       A proportional fit (y=ax) can be requested  instead  of  a\n"
"       full slope (y=ax+b), in which case no intercept map can be\n"
"       produced. The proportional fit will compute every possible\n"
"       value  of  y/x,  then  take  the median one. This has been\n"
"       found to be quite robust.\n"
"\n"
"       If you provide a dark frame to  subtract  from  all  input\n"
"       twilight  frames,  the proportional fit mode will be acti­\n"
"       vated automatically.\n"
"\n"
"       The recipe also produces a QC paf file containing the min,\n"
"       the max, the average, and the standard  deviation  of  the\n"
"       median values of the input frames.\n"
"\n"
"OPTIONS\n"
"       -o or --output 'filename'\n"
"             Change the output file base name. Default is 'flat':\n"
"\n"
"       -i or --intercepts\n"
"             Output a y-intercept map. This is a byproduct of the\n"
"             slope fit.\n"
"       \n"
"       -e or --errmap\n"
"             Output an error map from the linear fit. This  image\n"
"             contains for each pixel the residual sum of  squared\n"
"             errors for all fitted points.\n"
"\n"
"       -b or --pixmap\n"
"             Output  a bad pixel map. This is a byproduct  of the\n"
"             gain map. All pixels outside of a fixed  [0.5,  2.0]\n"
"             (inclusive) interval are tagged as bad.  The  output\n"
"             is a pixel map (i.e. a FITS file). If you  are   not\n"
"             satisfied with these threshold settings, use  -t  or\n"
"             --threshold to set other thresholds on the gain map.\n"
"\n"
"       -p or --prop\n"
"             Instead of trying to  fit  a  full  slope  (y=ax+b),\n"
"             only  a  proportional  slope (y=ax) will be  fitted.\n"
"             This option will be activated when dark  subtraction\n"
"             is requested.\n"
"\n"
"       -d filename or --dark filename\n"
"             Provide  a  dark  frame  to subtract from all  input\n"
"             twilight frames. Check that the dark frame you  pro­\n"
"             vide  uses  the  same exposure time as the  twilight\n"
"             frames. Proportional fit is activated in that  case.\n"
"\n"
"       -t or --threshold 'low high'\n"
"             Change the thresholding  values for  bad  pixel  map\n"
"             creation. These values are  referring  to normalized\n"
"             flat-field  values   that  should  lie  around  1.0.\n"
"             All pixels in the normalized flat-field which  value\n"
"             lies outside of this range are flagged as bad pixel.\n"
"             Defaults are 0.5 and 2.0.\n"
"\n\n";

