
#ifndef _PRODUCTS_ISAAC_H_
#define _PRODUCTS_ISAAC_H_


/* Structure holding label/key pairs */
static prodlist_t prodlist_isaac[] = {
{ procat_imag_sw_flat_interce, "MASTER_IMG_FLAT_INTERC", "intercept frame from flat-field fit" },
{ procat_imag_sw_flat_errmap, "MASTER_IMG_FLAT_ERRMAP", "error map frame from flat-field fit" },
{ procat_imag_sw_flat_result, "MASTER_IMG_FLAT", "master flat-field frame" },
{ procat_imag_sw_flat_badpix, "MASTER_IMG_FLAT_BADPIX", "bad pixel map" },
{ procat_imag_sw_flat_qc, "MASTER_IMG_FLAT_QC", "QC parameters for twflat" },
{ procat_imag_jitter_qc, "JITTER_QC", "jitter quality control level 1 parameters" },
{ procat_imag_sw_jitter_result, "COADDED_IMG", "jitter co-added image" },
{ procat_imag_sw_jitter_diff, "JITTER_DIFF", "jitter object - sky difference" },
{ procat_imag_detlin_coeff_C, "DETLIN_C", "image of detlin C coefficients" },
{ procat_imag_detlin_coeff_A, "DETLIN_A", "image of detlin A coefficients" },
{ procat_imag_detlin_coeff_Q, "DETLIN_Q", "image of detlin goodness of fit" },
{ procat_imag_detlin_coeff_B, "DETLIN_B", "image of detlin B coefficients" },
{ procat_imag_detlin_QC, "DETLIN_QC", "QC parameters file for detlin" },
{ procat_imag_lw_jitter_result, "LW_COADDED_IMG", "chop/nod co-added image" },
{ procat_imag_zpoint_qc, "ZPOINT_QC", "zero-point measurement" },
{ procat_imag_zpoint_result, "ZPOINT", "zero-point measurement" },
{ procat_imag_illum, "ILLUM_FRAME", "flat-field llumination correction image" },
{ procat_imag_bg, "SKY_BACKGROUND", "sky background measurements" },
{ procat_spec_sw_arc_qc, "ARC_QC", "sw_arc quality control parameters" },
{ procat_spec_sw_arc_coef, "ARC_COEF", "coefficients of distortion and dispersion" },
{ procat_spec_sw_arc_corr, "ARC_CORRECT", "distortion corrected image" },
{ procat_spec_sw_jitter_comb, "SPECTRA_COMBINED", "combined image" },
{ procat_spec_sw_jitter_qc, "SPJITTER_QC", "sw_spjitter quality control parameters" },
{ procat_spec_sw_jitter_extr, "SPEC_EXTRACTED", "extracted spectrum" },
{ procat_spec_sw_resp_effi, "RESP_FUNC_EFFI", "efficiency function signal" },
{ procat_spec_sw_resp_conv, "RESP_FUNC_CONV", "conversion function signal" },
{ procat_spec_sw_resp_extr, "RESP_FUNC_EXTR", "extracted spectrum" },
{ procat_spec_sw_resp_back, "RESP_FUNC_BACK", "extracted background" },
{ procat_spec_sw_flat, "MASTER_SP_FLAT", "master flatfield image" },
{ procat_spec_sw_flat_qc, "SP_FLAT_QC", "sw_spflat quality control parameters" },
{ procat_spec_sw_sttr_extract, "STAR_TRACE_EXTR", "extracted spectra" },
{ procat_spec_sw_sttr_corresp, "STAR_TRACE_CORR", "relations between star and spectra positions" },
{ procat_spec_sw_sttr_disto, "STAR_TRACE_COEF", "2d distortion relation" },
{ procat_spec_sw_sttr_qc, "STAR_TRACE_QC", "sw_startrace quality control parameters" },
{ procat_spec_sw_sttr_correct, "STAR_TRACE_CORRECT", "distortion corrected images" },
{ procat_spec_sw_sttr_shape, "STAR_TRACE_SHAPE", "polynomials that fit the spectra" },
{ procat_spec_sw_sttr_pos, "STAR_TRACE_POSI", "positions of stars and spectra" },
{ procat_spec_lw_arc_qc, "LW_ARC_QC", "lw_arc quality control parameters" },
{ procat_spec_lw_arc_coef, "LW_ARC_COEF", "coefficients of distortion and dispersion" },
{ procat_spec_lw_arc_corr, "LW_ARC_CORRECT", "distortion corrected image" },
{ procat_spec_lw_jitter_comb, "LW_SPECTRA_COMBINED", "combined image" },
{ procat_spec_lw_jitter_qc, "LW_SPJITTER_QC", "lw_spjitter quality control parameters" },
{ procat_spec_lw_jitter_extr, "LW_SPEC_EXTRACTED", "extracted spectrum" },
{ procat_spec_lw_resp_effi, "LW_RESP_FUNC_EFFI", "efficiency function signal" },
{ procat_spec_lw_resp_conv, "LW_RESP_FUNC_CONV", "conversion function signal" },
{ procat_spec_lw_resp_extr, "LW_RESP_FUNC_EXTR", "extracted spectrum" },
{ procat_spec_lw_resp_back, "LW_RESP_FUNC_BACK", "extracted background" },
{ procat_spec_lw_flat, "LW_MASTER_SP_FLAT", "master flatfield image" },
{ procat_spec_lw_flat_qc, "LW_SP_FLAT_QC", "lw_spflat quality control parameters" },
{ procat_spec_lw_sttr_extract, "LW_STAR_TRACE_EXTR", "extracted spectra" },
{ procat_spec_lw_sttr_corresp, "LW_STAR_TRACE_CORR", "relations between star and spectra positions" },
{ procat_spec_lw_sttr_disto, "LW_STAR_TRACE_COEF", "2d distortion relation" },
{ procat_spec_lw_sttr_qc, "LW_STAR_TRACE_QC", "lw_startrace quality control parameters" },
{ procat_spec_lw_sttr_correct, "LW_STAR_TRACE_CORRECT", "distortion corrected images" },
{ procat_spec_lw_sttr_shape, "LW_STAR_TRACE_SHAPE", "polynomials that fit the spectra" },
{ procat_spec_lw_sttr_pos, "LW_STAR_TRACE_POSI", "positions of stars and spectra" },
{ procat_spec_slitpos_qc, "SLITPOS_QC", "slitpos quality control parameters" },
{ procat_spec_slitpos_table, "SLIT_DESC", "slit exact position stored in a FITS table" },
{ procat_dark_ron, "MASTER_DARK_RON", "read-out noise measurements" },
{ procat_dark_result, "MASTER_DARK", "master dark frame" },
{ procat_end, NULL, NULL }
} ;


#endif
